# The device mesh — ONE source of truth for the three NixOS hosts, consumed by
# both the SSH trust plumbing (modules/mesh.nix) and the Remmina VNC profiles
# (home/remote.nix).
#
# Per host: `aliases` (every name/IP the host answers to) and two PUBLIC keys that
# are safe to commit. Fill them in once, AFTER a host's first boot:
#   hostKey — the box's SSH host key:   cat /etc/ssh/ssh_host_ed25519_key.pub
#   userKey — tom's SSH user key:        cat ~/.ssh/id_ed25519.pub   (ssh-keygen -t ed25519 if absent)
# Commit the two lines → every OTHER host then trusts this one with zero TOFU, and
# tom on this host can reach the others. Empty keys are simply skipped, so the config
# stays valid while a host is still un-flashed.
# Host keys were generated offline (2026-07-05); the private halves live in the
# operator recovery bundle and are delivered at install via
# `nixos-anywhere --extra-files`. userKey is the fleet SSH key rotated on
# 2026-07-29 after the previous key was exposed on a returned device. It is an SSH
# login key only, never an agenix editor recipient; see ../secrets.nix.
{
  coordinator = {
    aliases = [ "coordinator" ];
    hostKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFPCZFlnHQSNH3D0R1/qs9A/W498f8xTNUNBtLWZgU2A root@coordinator";
    userKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINwxGJ4IgTFfdMI+A2SDJO/E3jsZ7M/5McAioO87VX8Z tom@mesh-20260729";
  };
  nas = {
    aliases = [
      "nas"
      # Both transitional rails of the 2026-08-20 rewire: the LAN identity
      # and the legacy /30 (retires with the cleanup commit).
      "10.42.0.1"
      "10.77.0.2"
    ];
    # Generated on the appliance's first installed boot (2026-08-01) and read
    # over the direct /30 cable. Deliberately NOT --copy-host-keys: that would
    # have inherited key material first generated by the vendor OS.
    hostKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ0sfr0Sr5HaHKEAn/aO4qPbixN7PDYwIpuQvLlue4dU root@nas";
    # The appliance is inbound-only; coordinator deploys to it over the cable.
    userKey = "";
  };
  zenbook-duo = {
    aliases = [ "zenbook-duo" ];
    hostKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKvikHKjh49tlT9PDlG47hcRWyz8NX7uWw2ZhQoQJxxP root@zenbook-duo";
    userKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINwxGJ4IgTFfdMI+A2SDJO/E3jsZ7M/5McAioO87VX8Z tom@mesh-20260729";
  };
}
