{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
# programs.scroll — the fleet's own NixOS module for dawsers/scroll (master,
# pkgs/scroll via the overlay). Shaped after nixpkgs' programs.niri
# (nixos/modules/programs/wayland/niri.nix): a compositor that runs as a
# systemd user UNIT started by a `*-session` launcher, portals keyed on
# XDG_CURRENT_DESKTOP, gnome-keyring for Secret, wayland-session.nix for the
# polkit/dconf/graphical-desktop plumbing.
#
# Why our own module and not nixpkgs PR #544657's programs.scroll (unmerged,
# Diax170@54089750): two of its defaults are wrong for this fleet.
#   1. It writes /etc/scroll/config and /etc/scroll/config.d/nixos.conf, but
#      scroll's search path ends at the COMPILED-IN sysconfdir (the store path)
#      and the default config's `include …/config.d/*` is commented out, so
#      neither file is ever read. Here the RAW user config includes
#      /etc/scroll/config.d/* explicitly (home/dot_config/scroll/config), and
#      this module owns exactly one file there.
#   2. Its nixos.conf exports SWAYSOCK and I3SOCK into the systemd and D-Bus
#      activation environment. On the strix that environment also hosts
#      the headless browser SWAY (modules/browser-desktop.nix), so a bare
#      `swaymsg` from any user unit would reach scroll. Here only SCROLLSOCK is
#      exported.
# When the PR merges, `programs.scroll` becomes a duplicate option declaration
# and evaluation fails loudly — that is the signal to compare and retire one.
#
# Session shape (mirrors niri-session + niri.service):
#   greetd → scroll-session (login shell, so hm-session-vars load)
#     → import env into the user manager → `systemctl --user --wait start scroll.service`
#   scroll.service runs the compositor (restartIfChanged = false: a switch must
#     never kill the seat; enableDefaultPath = false: keep the imported PATH)
#   /etc/scroll/config.d/10-session.conf (exec'd by scroll once its socket and
#     WAYLAND_DISPLAY exist) → push WAYLAND_DISPLAY/DISPLAY/SCROLLSOCK into the
#     user manager + D-Bus, start scroll-session.target (BindsTo
#     graphical-session.target: portals, kanshi-free session units, piri-free)
#   compositor exit → scroll-shutdown.target stops graphical-session.target.
# herdr is WantedBy=default.target with no PartOf (home/herdr.nix, asserted in
# flake.nix), so none of this touches it.
let
  cfg = config.programs.scroll;

  # Variables pushed into the user manager once scroll is up. SCROLLSOCK only:
  # never SWAYSOCK / I3SOCK (see 2. above).
  sessionVars = [
    "WAYLAND_DISPLAY"
    "DISPLAY"
    "SCROLLSOCK"
    "XDG_CURRENT_DESKTOP"
    "XDG_SESSION_TYPE"
    "XDG_SESSION_DESKTOP"
  ];

  scroll-session = pkgs.writeShellScriptBin "scroll-session" ''
    # scroll-session — greetd's command for the physical scroll seat.
    # Shape copied from niri's resources/niri-session (GPL-3.0 upstream; this
    # is a re-statement of the systemd steps, not a copy of its text).

    # Re-exec through the login shell once, so ~/.bash_profile sources
    # hm-session-vars.sh before the environment is imported (as niri-session).
    if [ -n "''${SHELL:-}" ] && [ "''${1:-}" != -l ] \
      && grep -qx "$SHELL" /etc/shells && ! printf %s "$SHELL" | grep -q 'nologin\|false'; then
      exec "$SHELL" -l -c "exec $0 -l"
    fi

    if ${pkgs.systemd}/bin/systemctl --user -q is-active scroll.service; then
      echo 'A scroll session is already running.' >&2
      exit 1
    fi

    export XDG_CURRENT_DESKTOP=scroll XDG_SESSION_DESKTOP=scroll XDG_SESSION_TYPE=wayland
    # Never inherit a stale IPC path: a scroll started with SCROLLSOCK set
    # adopts it (sway/ipc-server.c:101).
    unset SCROLLSOCK SWAYSOCK I3SOCK NIRI_SOCKET

    ${pkgs.systemd}/bin/systemctl --user reset-failed
    # import-environment only adds: a NIRI_SOCKET left in the user manager by
    # an unclean niri exit would pass piri's ConditionEnvironment on scroll and
    # crash-loop it into tripwire. Drop it (and stale scroll/sway paths) first.
    ${pkgs.systemd}/bin/systemctl --user unset-environment NIRI_SOCKET SCROLLSOCK SWAYSOCK I3SOCK
    # The whole login environment, as niri-session does (PATH, hm-session-vars).
    ${pkgs.systemd}/bin/systemctl --user import-environment 2>/dev/null
    ${pkgs.dbus}/bin/dbus-update-activation-environment --all 2>/dev/null || true

    ${pkgs.systemd}/bin/systemctl --user --wait start scroll.service

    ${pkgs.systemd}/bin/systemctl --user start --job-mode=replace-irreversibly scroll-shutdown.target
    ${pkgs.systemd}/bin/systemctl --user unset-environment ${lib.concatStringsSep " " sessionVars} SWAYSOCK I3SOCK
  '';

  # The one file this module owns under /etc/scroll/config.d. Absolute store
  # paths: the compositor's PATH is the imported login PATH, but this must not
  # depend on it.
  sessionConf = ''
    # GENERATED by modules/scroll.nix. Included by ~/.config/scroll/config
    # (`include /etc/scroll/config.d/*`). SCROLLSOCK only — never SWAYSOCK/I3SOCK.
    exec ${pkgs.dbus}/bin/dbus-update-activation-environment --systemd ${lib.concatStringsSep " " sessionVars} && ${pkgs.systemd}/bin/systemctl --user start scroll-session.target
  '';

  # GNOME desktop pieces that must never ride in on a portal or Nautilus.
  forbiddenInClosure = [
    "gnome-shell"
    "mutter"
    "gnome-session"
    "gdm"
  ];
in
{
  options.programs.scroll = {
    enable = lib.mkEnableOption "scroll, a scrolling-tiling Wayland compositor (dawsers/scroll master)";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.scroll;
      defaultText = lib.literalExpression "pkgs.scroll";
      description = "The scroll package (pkgs/scroll, master pinned by rev).";
    };

    sessionPackage = lib.mkOption {
      type = lib.types.package;
      readOnly = true;
      default = scroll-session;
      description = "The scroll-session launcher greetd runs.";
    };

    useNautilus = lib.mkEnableOption "Nautilus as the FileChooser through xdg-desktop-portal-gnome" // {
      default = true;
    };

    closureGuard =
      lib.mkEnableOption "the build-time check that no GNOME shell/session/gdm package is in the system closure"
      // {
        default = true;
      };
  };

  config = lib.mkIf cfg.enable (
    lib.mkMerge [
      {
        assertions = [
          {
            assertion = !(config.services.desktopManager.gnome.enable or false);
            message = "programs.scroll: the GNOME desktop must not be enabled on a scroll seat (no gnome-shell/mutter/gnome-session).";
          }
          {
            assertion = !(config.services.displayManager.gdm.enable or false);
            message = "programs.scroll: gdm must not be enabled on a scroll seat; greetd launches scroll-session.";
          }
          {
            assertion =
              !(builtins.any (
                p: builtins.elem (lib.getName p) forbiddenInClosure
              ) config.environment.systemPackages);
            message = "programs.scroll: ${lib.concatStringsSep ", " forbiddenInClosure} must not be in environment.systemPackages.";
          }
          {
            # The headless browser desktop runs STOCK sway; scroll must never be
            # packaged by overriding it.
            assertion =
              (pkgs.sway-unwrapped.src.owner or "swaywm") != "dawsers"
              && (pkgs.sway-unwrapped.src.repo or "sway") != "scroll"
              && lib.getName pkgs.sway == "sway";
            message = "programs.scroll: pkgs.sway-unwrapped has been replaced by scroll's source; keep sway stock (modules/browser-desktop.nix).";
          }
        ];

        environment.systemPackages = [
          cfg.package
          scroll-session
        ];

        environment.etc."scroll/config.d/10-session.conf".text = sessionConf;

        # Required for xdg-desktop-portal-gnome's FileChooser (Nautilus) to work.
        services.dbus.packages = lib.mkIf cfg.useNautilus [ pkgs.nautilus ];

        services.gnome.gnome-keyring.enable = lib.mkDefault true;

        systemd.user.services.scroll = {
          description = "scroll, a scrolling-tiling Wayland compositor";
          wants = [ "graphical-session-pre.target" ];
          after = [ "graphical-session-pre.target" ];
          # Restarting the compositor kills the graphical session (niri module
          # and the display managers do the same).
          restartIfChanged = false;
          # Without this NixOS writes Environment=PATH=coreutils:… into the
          # unit and clobbers the login PATH scroll-session imported, breaking
          # every `exec` in the RAW config.
          enableDefaultPath = false;
          serviceConfig = {
            Type = "simple";
            Slice = "session.slice";
            ExecStart = "${cfg.package}/bin/scroll";
            # A compositor that dies stays dead; greetd/the getty are recovery.
            Restart = "no";
          };
        };

        systemd.user.targets.scroll-session = {
          description = "scroll compositor session";
          documentation = [ "man:systemd.special(7)" ];
          bindsTo = [ "graphical-session.target" ];
          wants = [
            "graphical-session-pre.target"
            "xdg-desktop-autostart.target"
          ];
          after = [ "graphical-session-pre.target" ];
          before = [ "xdg-desktop-autostart.target" ];
        };

        systemd.user.targets.scroll-shutdown = {
          description = "Shutdown running scroll session";
          conflicts = [
            "graphical-session.target"
            "graphical-session-pre.target"
            "scroll-session.target"
          ];
          after = [
            "graphical-session.target"
            "graphical-session-pre.target"
            "scroll-session.target"
          ];
          unitConfig = {
            DefaultDependencies = false;
            StopWhenUnneeded = true;
          };
        };

        xdg.portal = {
          enable = lib.mkDefault true;
          # XDG_CURRENT_DESKTOP=scroll selects this table (scroll-portals.conf).
          config.scroll = {
            default = [ "gtk" ];
            "org.freedesktop.impl.portal.FileChooser" = if cfg.useNautilus then "gnome" else "gtk";
            "org.freedesktop.impl.portal.ScreenCast" = "wlr";
            "org.freedesktop.impl.portal.Screenshot" = "wlr";
            "org.freedesktop.impl.portal.Secret" = "gnome-keyring";
            "org.freedesktop.impl.portal.Access" = "gtk";
            "org.freedesktop.impl.portal.Notification" = "gtk";
            "org.freedesktop.impl.portal.Settings" = "gtk";
          };
          extraPortals = lib.optionals cfg.useNautilus [ pkgs.xdg-desktop-portal-gnome ];
          # Output picker for screen sharing (Chrome "share screen"): without a
          # chooser xdpw offers nothing to pick on a two-output desk.
          wlr.settings.screencast = {
            chooser_type = "simple";
            chooser_cmd = "${pkgs.slurp}/bin/slurp -f %o -or";
          };
        };
      }

      (import "${modulesPath}/programs/wayland/wayland-session.nix" {
        inherit lib pkgs;
        enableWlrPortal = true;
        # scroll's vendored wlroots spawns the Xwayland it was built against.
        enableXWayland = false;
      })

      (lib.mkIf cfg.closureGuard {
        # Build-time proof, not just an eval-time list check: walk the closure
        # of the system profile and /etc (everything the toplevel carries
        # besides kernel/initrd) and fail if a GNOME shell, mutter,
        # gnome-session or gdm store path is in it. Portals and Nautilus pull
        # in plenty of GNOME libraries; these four are the desktop itself.
        system.checks = [
          (pkgs.runCommand "scroll-no-gnome-desktop-in-closure"
            {
              closure = pkgs.closureInfo {
                rootPaths = [
                  config.system.path
                  config.system.build.etc
                ];
              };
            }
            ''
              if grep -E '^/nix/store/[a-z0-9]{32}-(${lib.concatStringsSep "|" forbiddenInClosure})-[0-9]' "$closure/store-paths" > hits; then
                echo "programs.scroll closure guard: GNOME desktop packages in the system closure:" >&2
                cat hits >&2
                exit 1
              fi
              touch "$out"
            ''
          )
        ];
      })
    ]
  );
}
