#!/bin/bash
filename=~/Pictures/scrn-$(date +"%Y-%m-%d-%H:%M:%S").png

case "$1" in
    full)
        grim - | tee "$filename" | wl-copy
        notify-send "Full screenshot taken" -t 250
        ;;
    area)
        grim -g "$(slurp)" - | tee "$filename" | wl-copy
        notify-send "Area screenshot taken" -t 250
        ;;
    *)
        echo "Usage: $0 {full|area}"
        exit 1
        ;;
esac
