{
  config,
  inputs,
  lib,
  pkgs,
  osConfig,
  ...
}:
# Voxtype — dictation for the client, transcribed on the coordinator's GPU
# (#376, route b', DECISIONS 2026-09-13). The upstream Home Manager module owns
# the package, the generated TOML and the one systemd user service; every host
# imports the options, only the coordinator enables them.
#
# THE ROUTE. The mic is on the client (the Shift+F9 Audio Route picker selects
# it), the model is here. On Mod+Space the client's `dictate-hold` pipes its
# PipeWire default source over ONE ssh session into `voxtype-relay`
# (home/dot_local/bin), which arms this daemon with `record start --file=…`,
# plays the audio into the `client-mic` loopback declared below, stops on EOF,
# and prints the transcript back down the same ssh session; the client types
# it into the focused herdr projector with kitty remote control. No model, no
# voxtype package and no daemon on the client (flake.nix home-profiles).
#
# HEADLESS, so no display coupling any more: the gate is the coordinator
# alone (the old `&& myDisplay.enable` made this file inert at the R-13 flip),
# the evdev hotkey is off (the keyboard is on the client), there is no OSD
# frontend, and the unit hangs off default.target under linger instead of the
# graphical-session.target upstream wires it to.
let
  hostName = osConfig.networking.hostName;
  isDictationHost = hostName == "coordinator";
  package = inputs.voxtype.packages.${pkgs.stdenv.hostPlatform.system}.onnx-migraphx;
  # BATCH TDT v3, not the streaming parakeet-unified model this file used to
  # pin. Measured on this box 2026-09-13 with voxtype 0.7.5 against a 5.8 s
  # espeak fixture played into a loopback source:
  #   - streaming=true: `record start --file=PATH` writes nothing — the
  #     streaming chain is built from config.output (src/daemon.rs:915) and
  #     never reads the --file override, and mode="file" there falls back to
  #     the clipboard (src/output/mod.rs File arm);
  #   - streaming=false on parakeet-unified-en-0.6b: the batch ParakeetTDT
  #     loader accepts the directory and returns "" for every input (its
  #     files are encoder.onnx / decoder_joint.onnx, not the
  #     encoder-model.onnx layout the batch loader expects,
  #     src/transcribe/parakeet.rs:444-455);
  #   - streaming=false on parakeet-tdt-0.6b-v3: the exact sentence,
  #     punctuated, 0.21 s inference warm (3.2 s on the first call after
  #     load), ~280 ms from `record stop` to the file.
  # Streaming would buy nothing on this route anyway: the text is delivered on
  # release, not typed live. post_process works again in batch mode.
  # The old unified model stays in ~/.local/share/voxtype/models unused.
  parakeetModel = "parakeet-tdt-0.6b-v3";

  # The coordinator end of the audio seam. A loopback pair: `client-mic` is a
  # sink (voxtype-relay plays the client's audio into it), `client-mic-source`
  # is the matching source the daemon records from (PIPEWIRE_NODE below, so
  # the daemon never depends on which source is the default). Both at session
  # priority 0. Measured 2026-09-13: the default SINK stays the Ryzen analog
  # output, but the default SOURCE does become `client-mic-source` — every
  # source in WirePlumber's saved preference list (iContact, INZONE) moved to
  # the client's dock, and the Ryzen input has no available port, so the
  # coordinator had no default source at all before. Harmless on a headless
  # box: the only thing a stray default-source recorder here could hear is
  # dictation audio, and only while a key is held on the client.
  # A pipewire.conf.d drop-in is read at pipewire START: it goes live on the
  # next `systemctl --user restart pipewire pipewire-pulse wireplumber` or
  # reboot, not on the Home Manager switch.
  clientMicConf = ''
    # GENERATED by home/voxtype.nix (#376): the client's dictation mic, fed
    # over ssh by voxtype-relay, recorded by the voxtype daemon.
    context.modules = [
      { name = libpipewire-module-loopback
        args = {
          node.description = "Client dictation mic (ssh relay)"
          audio.rate = 16000
          audio.channels = 1
          audio.position = [ MONO ]
          capture.props = {
            node.name = "client-mic"
            media.class = "Audio/Sink"
            priority.session = 0
            priority.driver = 0
          }
          playback.props = {
            node.name = "client-mic-source"
            media.class = "Audio/Source"
            node.passive = true
            priority.session = 0
            priority.driver = 0
          }
        }
      }
    ]
  '';
in
{
  imports = [ inputs.voxtype.homeManagerModules.default ];

  programs.voxtype = lib.mkIf isDictationHost {
    enable = true;
    engine = "parakeet";
    inherit package;
    service.enable = true;

    settings = {
      # voxtype-relay polls $XDG_RUNTIME_DIR/voxtype/state to know when the
      # capture is open and when a transcription has finished.
      state_file = "auto";

      # The keyboard is on the client: `dictate-hold` there watches the
      # release and relays record start/stop. No evdev listener here.
      hotkey.enabled = false;

      # cpal's `default` device goes through pipewire-alsa, which honours
      # PIPEWIRE_NODE (set on the unit) — so the daemon records the
      # client-mic loopback without making it this host's default source.
      audio = {
        device = "default";
        # A held key is a sentence or a paragraph; five minutes is a stuck key.
        max_duration_secs = 300;
      };

      # Headless: no OSD child (it crash-loops looking for a Wayland seat).
      osd.enabled = false;

      parakeet = {
        model = parakeetModel;
        model_type = "tdt";
        streaming = false;
        on_demand_loading = false;
      };

      output = {
        # Every transcript leaves through `record start --file=…`; this mode
        # is only what a bare `voxtype record start` would do, and with no
        # display the clipboard is the harmless no-op.
        mode = "clipboard";
        fallback_to_clipboard = false;
        driver_order = [ "clipboard" ];
      };
    };
  };

  xdg.configFile."pipewire/pipewire.conf.d/60-client-mic.conf" = lib.mkIf isDictationHost {
    text = clientMicConf;
  };

  systemd.user.services.voxtype = lib.mkIf isDictationHost {
    Unit = {
      X-Restart-Triggers = [ config.xdg.configFile."voxtype/config.toml".source ];
      # Headless under linger: not part of a graphical session that never
      # starts here (upstream module: PartOf/WantedBy graphical-session.target).
      PartOf = lib.mkForce [ ];
      After = lib.mkForce [
        "pipewire.service"
        "pipewire-pulse.service"
      ];
      Wants = [ "pipewire.service" ];
    };

    Install.WantedBy = lib.mkForce [ "default.target" ];

    Service = {
      # Upstream sets Restart=on-failure/RestartSec=5; a failed model load is
      # a retried unit, never a boot blocker.
      Environment = [ "PIPEWIRE_NODE=client-mic-source" ];
      # `setup --download` also persists its selected model to the default
      # config path. Home Manager owns that path with an immutable store
      # symlink, so give setup a throw-away XDG config root while leaving
      # XDG_DATA_HOME untouched: the model still lands in Voxtype's canonical
      # ~/.local/share/voxtype/models directory and the daemon continues to use
      # the declarative config generated above.
      ExecStartPre = "${pkgs.coreutils}/bin/env XDG_CONFIG_HOME=%t/voxtype-bootstrap ${package}/bin/voxtype setup --download --model ${parakeetModel} --quiet";
      RuntimeDirectory = "voxtype-bootstrap";
      RuntimeDirectoryMode = "0700";
      # First start downloads 2.5 GB; later starts are a no-op check.
      TimeoutStartSec = "infinity";
    };
  };
}
