#!/usr/bin/env python3
"""A1 - KITTY RESOLUTION.  The gate the 2026-08-21 incident lacked.

    tests/resolve.py <out-dir>

Runs kitty's OWN resolver (`kitty +runpy`) against all 12 faces under TWO
fontconfig configurations and asserts four things:

 1. POSITIVE, the only hard gate.  The shipped kitty.conf, loaded through
    kitty.config.load_config, must give

        {'medium': 'AnthropicMonoNFM',
         'bold':   'AnthropicMonoNFM-SemiBold',
         'italic': 'AnthropicMonoNFM-Italic',
         'bi':     'AnthropicMonoNFM-SemiBoldItalic'}

    from get_font_files().  ALWAYS measure roles with get_font_files, NEVER a
    bare find_best_match: find_best_match's defaults are bold=False,
    italic=False, and that is what produced v1's phantom E20 bug.

 2. NEGATIVE, config-independent.  The forbidden long form must not be a key
    in the nameID6 / nameID4 / nameID1+16 maps:

        find_best_match('AnthropicMono Nerd Font Mono SemiBold',
                        bold=False, italic=False, monospaced=True)
            != 'AnthropicMonoNFM-SemiBold'

    Never "is not the Anthropic family": that is false under an isolated
    config (it resolves to -Bold/-BoldItalic) and false again after the
    defaultFonts commit.  And never the 4-tuple through get_font_files
    either - MEASURED HERE, on all 12 faces, in both configurations: the
    forbidden long form still yields the CORRECT 4-tuple, because
    get_font_files re-expands the single fc_match hit through family_map with
    the real bold/italic flags and no other monospace family is reachable.
    C2 saw LigaSFMono-SemiBold only under the LIVE system config.  The tuple
    is recorded as evidence; asserting on it would be a false failure.

 3. TYPO CANARY.  When the lowercase exact-match style filter empties the
    candidate list, find_best_match_in_candidates returns None and kitty falls
    silently to find_last_resort_text_font.  The four style spellings
    SemiBold / Italic / SemiBold Italic are load-bearing literals.
    The config-independent assertion is that style="Semi Bold" does NOT give
    the face the correct spelling gives.  C1's stronger wording ("resolves
    OUTSIDE the Anthropic family") holds only where a non-Anthropic monospace
    wins kitty's last resort: it is FALSE post-switch by construction, since
    the monospace alias then prefers AnthropicMono Nerd Font Mono.  Measured
    here, both configs: style="Semi Bold" -> AnthropicMonoNFM-Bold, i.e. the
    typo silently costs you two weights inside the right family.

 4. The review-window -o strings survive kitty.cli.parse_override and resolve
    to the same 4-tuple.

THE TWO CONFIGURATIONS
  alias-free    tests/fonts.conf.in over <out>/nf + <out>/desktop plus one
                non-Anthropic system font dir, no conf.d, no generic aliases.
                This is the shape of $P3/refute-C2/fcB.conf.
  post-switch   FAITHFUL, not simulated: /etc/fonts/fonts.conf is copied with
                its conf.d include repointed at a private conf.d that carries
                every system .conf EXCEPT 52-nixos-default-fonts.conf, which is
                replaced by the one this PR's `fonts.fontconfig.defaultFonts`
                would generate.  That is the only honest way to test the
                deployed state before switching.

MECHANICS
  `kitty +runpy` wants a tty, so every call is wrapped in
  `script -qec '...' /dev/null`.  The naive `kitty +runpy "$(cat file)"` form
  breaks on the embedded quotes of the family="..." settings, so the probe is
  exec'd from a file by path instead.  No compositor is spawned and no kitty
  window is opened: +runpy is headless python inside kitty's runtime.

  fc-cache is never invoked.  FONTCONFIG_FILE and XDG_CACHE_HOME are both
  redirected under <out>/verify.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import subprocess
import sys

# Patcher 3.5.1 added FontnameParser._remove_regular: the RIBBI Regular face
# ships the BARE PostScript name, no -Regular token.  The Regular-weight
# italic is still -Italic and every other face keeps its -<Style> suffix.
WANT = {"medium": "AnthropicMonoNFM",
        "bold": "AnthropicMonoNFM-SemiBold",
        "italic": "AnthropicMonoNFM-Italic",
        "bi": "AnthropicMonoNFM-SemiBoldItalic"}

KITTY_CONF = """# generated by tests/resolve.py - the SHIPPED four lines, verbatim (spec 2.4)
font_family      family="AnthropicMono Nerd Font Mono"
bold_font        family="AnthropicMono Nerd Font Mono" style="SemiBold"
italic_font      family="AnthropicMono Nerd Font Mono" style="Italic"
bold_italic_font family="AnthropicMono Nerd Font Mono" style="SemiBold Italic"
font_size 16.0
disable_ligatures never
"""

DEFAULT_FONTS = """<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'urn:fontconfig:fonts.dtd'>
<fontconfig>
  <!-- exactly as NixOS regenerates 52-nixos-default-fonts.conf from this PR's
       fonts.fontconfig.defaultFonts (spec 2.5 / 7.8) -->
  <alias binding="same"><family>sans-serif</family><prefer>
    <family>Anthropic Sans</family>
    <family>SF Pro Display</family>
    <family>SF Pro Text</family>
  </prefer></alias>
  <alias binding="same"><family>serif</family><prefer>
    <family>Anthropic Serif</family>
    <family>Source Serif 4</family>
  </prefer></alias>
  <alias binding="same"><family>monospace</family><prefer>
    <family>AnthropicMono Nerd Font Mono</family>
    <family>Liga SFMono Nerd Font</family>
  </prefer></alias>
  <alias binding="same"><family>emoji</family><prefer>
    <family>Noto Color Emoji</family>
  </prefer></alias>
</fontconfig>
"""

PROBE = r'''
import json, os
from kitty.config import load_config
from kitty.cli import parse_override
from kitty.fonts.common import get_font_files, FontSpec
from kitty.fonts.fontconfig import find_best_match
from kitty.options.types import Options

def roles(*settings):
    o = Options()
    o.font_family = FontSpec.from_setting(settings[0])
    o.bold_font = FontSpec.from_setting(settings[1])
    o.italic_font = FontSpec.from_setting(settings[2])
    o.bold_italic_font = FontSpec.from_setting(settings[3])
    ff = get_font_files(o)
    return ({k: ff[k].get("postscript_name") for k in ("medium", "bold", "italic", "bi")},
            {k: ff[k].get("family") for k in ("medium", "bold", "italic", "bi")})

res = {}

# 1 POSITIVE - the real shipped file through load_config
opts = load_config(os.environ["A1_KITTY_CONF"])
ff = get_font_files(opts)
res["positive"] = {k: ff[k].get("postscript_name") for k in ("medium", "bold", "italic", "bi")}
res["positive_files"] = {k: os.path.basename(ff[k].get("path", "")) for k in ("medium", "bold", "italic", "bi")}
res["font_size"] = opts.font_size

# 2 NEGATIVE - the forbidden long form, two ways
m = find_best_match("AnthropicMono Nerd Font Mono SemiBold", bold=False, italic=False, monospaced=True)
res["forbidden_find_best_match"] = m.get("postscript_name")
res["forbidden_tuple"], res["forbidden_families"] = roles(
    "AnthropicMono Nerd Font Mono",
    "AnthropicMono Nerd Font Mono SemiBold",
    "AnthropicMono Nerd Font Mono Italic",
    "AnthropicMono Nerd Font Mono SemiBold Italic")

# 3 TYPO CANARY - one space, silently wrong
res["canary_tuple"], res["canary_families"] = roles(
    'family="AnthropicMono Nerd Font Mono"',
    'family="AnthropicMono Nerd Font Mono" style="Semi Bold"',
    'family="AnthropicMono Nerd Font Mono" style="Italic"',
    'family="AnthropicMono Nerd Font Mono" style="SemiBold Italic"')

# 4 the review-window -o strings
RAW = (
    'font_family=family="AnthropicMono Nerd Font Mono"',
    'bold_font=family="AnthropicMono Nerd Font Mono" style="SemiBold"',
    'italic_font=family="AnthropicMono Nerd Font Mono" style="Italic"',
    'bold_italic_font=family="AnthropicMono Nerd Font Mono" style="SemiBold Italic"',
    'font_size=16.0',
    'disable_ligatures=never',
    'window_padding_width=14',
)
bad = []
ov = tuple(parse_override(x) for x in RAW)
o2 = load_config(overrides=ov, accumulate_bad_lines=bad)
ff2 = get_font_files(o2)
res["override_tuple"] = {k: ff2[k].get("postscript_name") for k in ("medium", "bold", "italic", "bi")}
res["override_bad_lines"] = [str(b.line) for b in bad]
res["override_parsed"] = [list(x) if isinstance(x, (list, tuple)) else str(x) for x in ov]

open(os.environ["A1_JSON"], "w").write(json.dumps(res, indent=1, default=str))
'''


def system_font_dirs():
    """<dir> entries fontconfig's own files declare, in declaration order."""
    dirs = []
    for p in ["/etc/fonts/fonts.conf", "/etc/fonts/conf.d/00-nixos-cache.conf"]:
        try:
            text = open(p).read()
        except OSError:
            continue
        for d in re.findall(r"<dir>([^<]+)</dir>", text):
            if os.path.isdir(d) and d not in dirs:
                dirs.append(d)
    return dirs


def write_aliasfree(tpl, out, verify, cachedir):
    """fcB.conf's shape: private cache, the faces under test, one neighbour."""
    neighbour = None
    for d in system_font_dirs():
        if "dejavu" in d:
            neighbour = d
            break
    if neighbour is None:
        sysdirs = system_font_dirs()
        neighbour = sysdirs[0] if sysdirs else None
    dirs = [os.path.join(out, "nf"), os.path.join(out, "desktop")]
    if neighbour:
        dirs.append(neighbour)
    os.makedirs(cachedir, exist_ok=True)
    body = "\n".join("  <dir>%s</dir>" % d for d in dirs)
    path = os.path.join(verify, "fonts-a1-aliasfree.conf")
    with open(path, "w") as fh:
        fh.write(tpl.replace("@CACHEDIR@", cachedir).replace("@FONTDIR@", body))
    return path, neighbour


def write_postswitch(out, verify, cachedir):
    """Faithful post-switch config: real /etc/fonts/fonts.conf, real conf.d,
    52-nixos-default-fonts.conf swapped for the one this PR generates."""
    root = os.path.join(verify, "postswitch")
    confd = os.path.join(root, "conf.d")
    os.makedirs(confd, exist_ok=True)
    os.makedirs(cachedir, exist_ok=True)
    for n in sorted(os.listdir("/etc/fonts/conf.d")):
        dst = os.path.join(confd, n)
        if os.path.lexists(dst):
            os.unlink(dst)
        if n == "52-nixos-default-fonts.conf":
            with open(dst, "w") as fh:
                fh.write(DEFAULT_FONTS)
            continue
        os.symlink(os.path.realpath(os.path.join("/etc/fonts/conf.d", n)), dst)
    text = open("/etc/fonts/fonts.conf").read()
    text = re.sub(r'<include[^>]*>\s*/etc/fonts/conf\.d\s*</include>',
                  '<include ignore_missing="yes">%s</include>' % confd, text)
    text = re.sub(r'<cachedir[^>]*>[^<]*</cachedir>', '', text)
    extra = ("  <cachedir>%s</cachedir>\n"
             "  <dir>%s</dir>\n  <dir>%s</dir>\n" % (cachedir, os.path.join(out, "nf"),
                                                     os.path.join(out, "desktop")))
    text = text.replace("</fontconfig>", extra + "</fontconfig>")
    path = os.path.join(verify, "fonts-a1-postswitch.conf")
    with open(path, "w") as fh:
        fh.write(text)
    if '<include ignore_missing="yes">%s</include>' % confd not in text:
        print("FAIL A1 post-switch: could not repoint the conf.d include in "
              "/etc/fonts/fonts.conf - the config is NOT faithful", file=sys.stderr)
    return path


def run_probe(conf, xdg, kitty_conf, probe, jsonpath):
    env = dict(os.environ)
    env["FONTCONFIG_FILE"] = conf
    env["XDG_CACHE_HOME"] = xdg
    env.pop("FONTCONFIG_PATH", None)
    env["A1_KITTY_CONF"] = kitty_conf
    env["A1_JSON"] = jsonpath
    if os.path.exists(jsonpath):
        os.unlink(jsonpath)
    inner = ("exec(compile(open(%s).read(), 'a1_probe', 'exec'), {'__name__': '__main__'})"
             % repr(probe))
    cmd = "kitty +runpy " + shlex.quote(inner)
    # kitty +runpy wants a tty.  A spawn that yields no JSON is retried once
    # before it is believed: measured, one spawn in several hundred came back
    # empty with no diagnostic, and that must not read as a resolution failure.
    p = None
    for attempt in range(2):
        if os.path.exists(jsonpath):
            os.unlink(jsonpath)
        p = subprocess.run(["script", "-qec", cmd, "/dev/null"],
                           capture_output=True, text=True, env=env, check=False)
        if os.path.exists(jsonpath):
            with open(jsonpath) as fh:
                return json.load(fh), p
        if attempt == 0:
            print("resolve: kitty produced no JSON, retrying once", file=sys.stderr)
    return None, p


def main(argv):
    # The driver invokes every test uniformly, so --src and --allow-partial are
    # ACCEPTED here even though A1 needs neither: --src names the read-only
    # capture dir (only A5's negative control uses it) and is ignored.
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--src", default=None, help="accepted and ignored; A1 needs no source")
    ap.add_argument("--allow-partial", action="store_true",
                    help="the out-dir holds a SUBSET of the faces. A1 is a 12-face gate and "
                         "cannot be judged on a subset, so it reports and exits 0.")
    a = ap.parse_args(argv[1:])
    out = os.path.abspath(a.out)

    nf = os.path.join(out, "nf")
    n_faces = len([x for x in os.listdir(nf) if x.endswith(".ttf")]) if os.path.isdir(nf) else 0
    if a.allow_partial and n_faces < 12:
        print("NOTE A1: %d of 12 terminal faces present. A1 resolves the four ROLES against "
              "the whole family, so a subset cannot answer it - the bold role would silently "
              "resolve to whatever weight happens to be installed. NOT judged." % n_faces)
        return 0
    verify = os.path.join(out, "verify")
    xdg = os.path.join(verify, "xdg")
    os.makedirs(xdg, exist_ok=True)
    here = os.path.dirname(os.path.abspath(__file__))
    tpl = open(os.path.join(here, "fonts.conf.in")).read()

    kitty_conf = os.path.join(verify, "kitty.conf")
    with open(kitty_conf, "w") as fh:
        fh.write(KITTY_CONF)
    probe = os.path.join(verify, "a1_probe.py")
    with open(probe, "w") as fh:
        fh.write(PROBE)

    aliasfree, neighbour = write_aliasfree(tpl, out, verify,
                                           os.path.join(verify, "cache-a1-aliasfree"))
    postswitch = write_postswitch(out, verify, os.path.join(verify, "cache-a1-postswitch"))

    fails, report = [], {"neighbour_dir": neighbour}
    for label, conf in (("alias-free", aliasfree), ("post-switch", postswitch)):
        res, p = run_probe(conf, xdg, kitty_conf,
                           probe, os.path.join(verify, "a1-%s.json" % label))
        if res is None:
            fails.append("A1 %s: the probe produced no JSON. kitty stderr: %s"
                         % (label, (p.stderr or p.stdout or "").strip()[-600:]))
            continue
        report[label] = res

        # 1 POSITIVE - the hard gate, in BOTH configurations
        if res["positive"] != WANT:
            fails.append("A1 %s POSITIVE: the shipped kitty.conf resolves to %s, expected %s"
                         % (label, res["positive"], WANT))

        # 2 NEGATIVE - the CONFIG-INDEPENDENT form, and only that form.
        # "the forbidden long form does not produce the 4-tuple" is true of
        # get_font_files ONLY when some other family wins the fc_match
        # fallthrough (C2 measured LigaSFMono-SemiBold under the LIVE system
        # config).  Under an alias-free config over these faces alone, and
        # again after the defaultFonts commit, no other monospace family is
        # reachable, so get_font_files re-expands through family_map with the
        # real bold/italic flags and recovers the right faces anyway - that is
        # exactly the D18/E20 mechanism.  Asserting on the 4-tuple here would
        # therefore be a false failure.  The stable statement is the bare
        # find_best_match with kitty's own default flags.
        if res["forbidden_find_best_match"] == "AnthropicMonoNFM-SemiBold":
            fails.append("A1 %s NEGATIVE: find_best_match('AnthropicMono Nerd Font Mono "
                         "SemiBold', bold=False, italic=False, monospaced=True) returned "
                         "AnthropicMonoNFM-SemiBold - the forbidden long form must not be a "
                         "key in the nameID6/nameID4/nameID1+16 maps" % label)
        if res["forbidden_tuple"] == WANT:
            report.setdefault("notes", []).append(
                "A1 %s: the forbidden long form still yields the correct 4-tuple through "
                "get_font_files, because no other monospace family is reachable in this "
                "configuration.  Recorded as evidence, not asserted (C2/D18)." % label)

        # 3 TYPO CANARY - one space, silently wrong.
        # The CONFIG-INDEPENDENT statement is "the typo does not give you the
        # face the correct spelling gives".  C1's stronger wording ("resolves
        # OUTSIDE the Anthropic family") holds only where a non-Anthropic
        # monospace wins kitty's last resort - true on the live system, FALSE
        # post-switch by construction, since the monospace alias then prefers
        # AnthropicMono Nerd Font Mono.
        fam = res["canary_families"].get("bold") or ""
        ps = res["canary_tuple"].get("bold") or ""
        if ps == WANT["bold"]:
            fails.append("A1 %s CANARY: style=\"Semi Bold\" resolved to %s, the same face "
                         "the correct spelling gives - the typo would be invisible"
                         % (label, ps))
        if res["canary_tuple"] == WANT:
            fails.append("A1 %s CANARY: the typo'd settings produced the full correct "
                         "4-tuple" % label)
        report.setdefault("notes", []).append(
            "A1 %s: canary style=\"Semi Bold\" -> family %r ps %r (correct spelling gives "
            "%s)" % (label, fam, ps, WANT["bold"]))

        # 4 the review-window override strings
        if res["override_bad_lines"]:
            fails.append("A1 %s OVERRIDE: parse_override produced bad config lines %s"
                         % (label, res["override_bad_lines"]))
        if res["override_tuple"] != WANT:
            fails.append("A1 %s OVERRIDE: the review-window -o strings resolve to %s, "
                         "expected %s" % (label, res["override_tuple"], WANT))

    with open(os.path.join(verify, "resolve.json"), "w") as fh:
        json.dump({"report": report, "failures": fails}, fh, indent=1, default=str)
    for label in ("alias-free", "post-switch"):
        if label in report:
            print("%-12s positive=%s" % (label, report[label]["positive"]))
            print("%-12s forbidden=%s" % ("", report[label]["forbidden_tuple"]))
            print("%-12s canary bold=%s / %s" % ("", report[label]["canary_families"].get("bold"),
                                                 report[label]["canary_tuple"].get("bold")))
    for f in fails:
        print("FAIL", f)
    print("resolve: %d failure(s) -> %s/resolve.json" % (len(fails), verify))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
