# The palette source of truth and the per-consumer renderers.
#
# Three hand-curated themes, no generation from wallpapers: each *.nix here is a
# plain attrset keyed by ROLE (fg, comment, red, ground.base, …), never by
# consumer. `render` turns one palette into the color FRAGMENT each app
# includes; home/theme.nix writes every fragment for every theme under
# ~/.config/themes/<name>/ and the RAW config files join theirs through the
# app's own include of ~/.config/theme/<fragment>, a symlink ~/.local/bin/theme
# flips at runtime. Design: docs/theme-switcher-2026-09-17.md.
#
# Pure: `{ lib }` only, so a preview can be rendered with a bare `nix eval`
# before any switch (see the doc's "Testing before a switch").
{ lib }:
let
  header = t: mark: "${mark} GENERATED by home/theme.nix from home/themes/${t.name}.nix — edit the palette, not this file.";

  kitty = t: ''
    ${header t "#"}
    # Joined by kitty.conf's `include ''${HOME}/.config/theme/kitty.conf`.
    background ${t.ground.base}
    foreground ${t.fg}
    selection_background ${t.selection.bg}
    selection_foreground ${t.selection.fg}
    cursor ${t.cursor}
    cursor_text_color ${t.cursorText}
    cursor_trail_color ${t.accent}
    url_color ${t.accent}

    # black
    color0 ${t.ansi.black}
    color8 ${t.ansi.brightBlack}
    # red
    color1 ${t.red}
    color9 ${t.red}
    # green
    color2 ${t.green}
    color10 ${t.green}
    # yellow
    color3 ${t.yellow}
    color11 ${t.yellow}
    # blue
    color4 ${t.blue}
    color12 ${t.blue}
    # magenta
    color5 ${t.magenta}
    color13 ${t.magenta}
    # cyan
    color6 ${t.cyan}
    color14 ${t.cyan}
    # white
    color7 ${t.ansi.white}
    color15 ${t.ansi.brightWhite}

    # tabs
    active_tab_background ${t.ground.base}
    active_tab_foreground ${t.fg}
    inactive_tab_background ${t.ground.dim}
    inactive_tab_foreground ${t.comment}
    tab_bar_background ${t.ground.dim}

    # marks
    mark1_foreground ${t.ground.base}
    mark1_background ${t.magenta}

    # splits: the divider matches niri's INACTIVE window border, so a kitty
    # split reads as a quiet niri-native divider (Tom 2026-07-15).
    active_border_color ${t.border.inactive}
    inactive_border_color ${t.ground.base}
  '';

  niri = t: ''
    ${header t "//"}
    // Joined by niri/config.kdl's `include optional=true "~/.config/theme/niri.kdl"`,
    // LAST, so these merge over layout.kdl / misc.kdl (niri merges sections
    // across includes; later wins per property — wiki, Configuration: Include).
    layout {
        border {
            on
            active-color "${t.border.active}"
            inactive-color "${t.border.inactive}"
            urgent-color "${t.border.urgent}"
        }
        tab-indicator {
            active-color "${t.tabIndicator.active}"
            inactive-color "${t.tabIndicator.inactive}"
            urgent-color "${t.border.urgent}"
        }
        insert-hint {
            color "${t.insertHint}"
        }
        background-color "${t.ground.desktop}"
    }
    overview {
        backdrop-color "${t.ground.desktop}"
    }
  '';

  # fish wants bare hex, no '#'.
  bare = c: lib.removePrefix "#" c;
  fish = t: ''
    ${header t "#"}
    # Sourced by fish/conf.d/colors.fish (which also re-sources it when the
    # ~/.config/theme symlink moves). Roles follow the nvim/kitty mapping.
    set -g fish_color_normal ${bare t.fg}
    set -g fish_color_command ${bare t.blue}
    set -g fish_color_param ${bare t.green}
    set -g fish_color_keyword ${bare t.red}
    set -g fish_color_quote ${bare t.green}
    set -g fish_color_end ${bare t.orange}
    set -g fish_color_comment ${bare t.comment}
    set -g fish_color_error ${bare t.red}
    set -g fish_color_option ${bare t.green}
    set -g fish_color_cancel ${bare t.red}
    set -g fish_color_cwd ${bare t.yellow}
    set -g fish_color_user ${bare t.cyan}
    set -g fish_color_host ${bare t.blue}
    set -g fish_color_host_remote ${bare t.green}
    set -g fish_color_status ${bare t.red}
    set -g fish_pager_color_completion ${bare t.fg}
  '';

  q = s: ''"${s}"'';
  lua = t: ''
    ${header t "--"}
    -- dofile()'d by nvim/lua/theme.lua; returns the palette as a Lua table.
    return {
      name = ${q t.name},
      polarity = ${q t.polarity},
      catppuccinFlavour = ${q t.catppuccinFlavour},
      ground = { base = ${q t.ground.base}, dim = ${q t.ground.dim}, raised = ${q t.ground.raised}, desktop = ${q t.ground.desktop} },
      fg = ${q t.fg}, fgDim = ${q t.fgDim}, comment = ${q t.comment}, muted = ${q t.muted},
      red = ${q t.red}, green = ${q t.green}, yellow = ${q t.yellow}, blue = ${q t.blue},
      magenta = ${q t.magenta}, cyan = ${q t.cyan}, orange = ${q t.orange},
      accent = ${q t.accent}, brand = ${q t.brand},
      selection = { bg = ${q t.selection.bg}, fg = ${q t.selection.fg} },
      border = { active = ${q t.border.active}, inactive = ${q t.border.inactive}, urgent = ${q t.border.urgent} },
    }
  '';

  # key=value, read by ~/.local/bin/theme with `read`, never sourced.
  # icon_suffix: the MacTahoe icon dirs are MacTahoe[-<accent>]-{dark,light};
  # the accent comes from `wallpaper`, the polarity from here.
  meta = t: ''
    name=${t.name}
    polarity=${t.polarity}
    claude_code=${t.claudeCode}
    gtk_theme=${t.gtk.theme}
    color_scheme=${t.gtk.colorScheme}
    icon_suffix=${if t.polarity == "light" then "light" else "dark"}
  '';
in
rec {
  themes = {
    noir = import ./noir.nix;
    claude-dark = import ./claude-dark.nix;
    claude-light = import ./claude-light.nix;
  };

  # Every theme must fill every role: a missing key would surface as a Nix
  # eval error deep in a string interpolation, so check up front.
  roles = [ "name" "polarity" "catppuccinFlavour" "claudeCode" "ground" "fg" "fgDim" "comment" "muted"
    "red" "green" "yellow" "blue" "magenta" "cyan" "orange" "accent" "brand" "ansi" "selection"
    "cursor" "cursorText" "border" "tabIndicator" "insertHint" "gtk" ];
  checked = lib.mapAttrs (n: t:
    let missing = lib.filter (r: !(t ? ${r})) roles;
    in if missing == [ ] && t.name == n then t
       else throw "home/themes/${n}.nix: name=${t.name}, missing roles: ${toString missing}") themes;

  render = t: {
    "kitty.conf" = kitty t;
    "niri.kdl" = niri t;
    "colors.fish" = fish t;
    "theme.lua" = lua t;
    "meta" = meta t;
  };

  # { "themes/<name>/<fragment>" = text; } for every theme — what theme.nix emits.
  fragments = lib.concatMapAttrs (name: t:
    lib.mapAttrs' (f: text: lib.nameValuePair "themes/${name}/${f}" text) (render t)) checked;
}
