// Code generated by ent, DO NOT EDIT.

package event

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mecattaf/dcal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldID, id))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUID, v))
}

// RemoteID applies equality check predicate on the "remote_id" field. It's identical to RemoteIDEQ.
func RemoteID(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRemoteID, v))
}

// Etag applies equality check predicate on the "etag" field. It's identical to EtagEQ.
func Etag(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldEtag, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldSummary, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldDescription, v))
}

// Location applies equality check predicate on the "location" field. It's identical to LocationEQ.
func Location(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldLocation, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldURL, v))
}

// MeetingURL applies equality check predicate on the "meeting_url" field. It's identical to MeetingURLEQ.
func MeetingURL(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldMeetingURL, v))
}

// Start applies equality check predicate on the "start" field. It's identical to StartEQ.
func Start(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldStart, v))
}

// End applies equality check predicate on the "end" field. It's identical to EndEQ.
func End(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldEnd, v))
}

// AllDay applies equality check predicate on the "all_day" field. It's identical to AllDayEQ.
func AllDay(v bool) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldAllDay, v))
}

// StartTz applies equality check predicate on the "start_tz" field. It's identical to StartTzEQ.
func StartTz(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldStartTz, v))
}

// EndTz applies equality check predicate on the "end_tz" field. It's identical to EndTzEQ.
func EndTz(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldEndTz, v))
}

// RecurringID applies equality check predicate on the "recurring_id" field. It's identical to RecurringIDEQ.
func RecurringID(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRecurringID, v))
}

// OriginalStart applies equality check predicate on the "original_start" field. It's identical to OriginalStartEQ.
func OriginalStart(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldOriginalStart, v))
}

// Transparency applies equality check predicate on the "transparency" field. It's identical to TransparencyEQ.
func Transparency(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldTransparency, v))
}

// Visibility applies equality check predicate on the "visibility" field. It's identical to VisibilityEQ.
func Visibility(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldVisibility, v))
}

// CrmRef applies equality check predicate on the "crm_ref" field. It's identical to CrmRefEQ.
func CrmRef(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCrmRef, v))
}

// CrmKind applies equality check predicate on the "crm_kind" field. It's identical to CrmKindEQ.
func CrmKind(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCrmKind, v))
}

// RawIcs applies equality check predicate on the "raw_ics" field. It's identical to RawIcsEQ.
func RawIcs(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRawIcs, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreated, v))
}

// Updated applies equality check predicate on the "updated" field. It's identical to UpdatedEQ.
func Updated(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUpdated, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldUID, v))
}

// UIDContains applies the Contains predicate on the "uid" field.
func UIDContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldUID, v))
}

// UIDHasPrefix applies the HasPrefix predicate on the "uid" field.
func UIDHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldUID, v))
}

// UIDHasSuffix applies the HasSuffix predicate on the "uid" field.
func UIDHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldUID, v))
}

// UIDEqualFold applies the EqualFold predicate on the "uid" field.
func UIDEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldUID, v))
}

// UIDContainsFold applies the ContainsFold predicate on the "uid" field.
func UIDContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldUID, v))
}

// RemoteIDEQ applies the EQ predicate on the "remote_id" field.
func RemoteIDEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRemoteID, v))
}

// RemoteIDNEQ applies the NEQ predicate on the "remote_id" field.
func RemoteIDNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldRemoteID, v))
}

// RemoteIDIn applies the In predicate on the "remote_id" field.
func RemoteIDIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldRemoteID, vs...))
}

// RemoteIDNotIn applies the NotIn predicate on the "remote_id" field.
func RemoteIDNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldRemoteID, vs...))
}

// RemoteIDGT applies the GT predicate on the "remote_id" field.
func RemoteIDGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldRemoteID, v))
}

// RemoteIDGTE applies the GTE predicate on the "remote_id" field.
func RemoteIDGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldRemoteID, v))
}

// RemoteIDLT applies the LT predicate on the "remote_id" field.
func RemoteIDLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldRemoteID, v))
}

// RemoteIDLTE applies the LTE predicate on the "remote_id" field.
func RemoteIDLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldRemoteID, v))
}

// RemoteIDContains applies the Contains predicate on the "remote_id" field.
func RemoteIDContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldRemoteID, v))
}

// RemoteIDHasPrefix applies the HasPrefix predicate on the "remote_id" field.
func RemoteIDHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldRemoteID, v))
}

// RemoteIDHasSuffix applies the HasSuffix predicate on the "remote_id" field.
func RemoteIDHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldRemoteID, v))
}

// RemoteIDIsNil applies the IsNil predicate on the "remote_id" field.
func RemoteIDIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldRemoteID))
}

// RemoteIDNotNil applies the NotNil predicate on the "remote_id" field.
func RemoteIDNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldRemoteID))
}

// RemoteIDEqualFold applies the EqualFold predicate on the "remote_id" field.
func RemoteIDEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldRemoteID, v))
}

// RemoteIDContainsFold applies the ContainsFold predicate on the "remote_id" field.
func RemoteIDContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldRemoteID, v))
}

// EtagEQ applies the EQ predicate on the "etag" field.
func EtagEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldEtag, v))
}

// EtagNEQ applies the NEQ predicate on the "etag" field.
func EtagNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldEtag, v))
}

// EtagIn applies the In predicate on the "etag" field.
func EtagIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldEtag, vs...))
}

// EtagNotIn applies the NotIn predicate on the "etag" field.
func EtagNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldEtag, vs...))
}

// EtagGT applies the GT predicate on the "etag" field.
func EtagGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldEtag, v))
}

// EtagGTE applies the GTE predicate on the "etag" field.
func EtagGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldEtag, v))
}

// EtagLT applies the LT predicate on the "etag" field.
func EtagLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldEtag, v))
}

// EtagLTE applies the LTE predicate on the "etag" field.
func EtagLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldEtag, v))
}

// EtagContains applies the Contains predicate on the "etag" field.
func EtagContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldEtag, v))
}

// EtagHasPrefix applies the HasPrefix predicate on the "etag" field.
func EtagHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldEtag, v))
}

// EtagHasSuffix applies the HasSuffix predicate on the "etag" field.
func EtagHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldEtag, v))
}

// EtagIsNil applies the IsNil predicate on the "etag" field.
func EtagIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldEtag))
}

// EtagNotNil applies the NotNil predicate on the "etag" field.
func EtagNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldEtag))
}

// EtagEqualFold applies the EqualFold predicate on the "etag" field.
func EtagEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldEtag, v))
}

// EtagContainsFold applies the ContainsFold predicate on the "etag" field.
func EtagContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldEtag, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldSummary, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldDescription, v))
}

// LocationEQ applies the EQ predicate on the "location" field.
func LocationEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldLocation, v))
}

// LocationNEQ applies the NEQ predicate on the "location" field.
func LocationNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldLocation, v))
}

// LocationIn applies the In predicate on the "location" field.
func LocationIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldLocation, vs...))
}

// LocationNotIn applies the NotIn predicate on the "location" field.
func LocationNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldLocation, vs...))
}

// LocationGT applies the GT predicate on the "location" field.
func LocationGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldLocation, v))
}

// LocationGTE applies the GTE predicate on the "location" field.
func LocationGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldLocation, v))
}

// LocationLT applies the LT predicate on the "location" field.
func LocationLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldLocation, v))
}

// LocationLTE applies the LTE predicate on the "location" field.
func LocationLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldLocation, v))
}

// LocationContains applies the Contains predicate on the "location" field.
func LocationContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldLocation, v))
}

// LocationHasPrefix applies the HasPrefix predicate on the "location" field.
func LocationHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldLocation, v))
}

// LocationHasSuffix applies the HasSuffix predicate on the "location" field.
func LocationHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldLocation, v))
}

// LocationIsNil applies the IsNil predicate on the "location" field.
func LocationIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldLocation))
}

// LocationNotNil applies the NotNil predicate on the "location" field.
func LocationNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldLocation))
}

// LocationEqualFold applies the EqualFold predicate on the "location" field.
func LocationEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldLocation, v))
}

// LocationContainsFold applies the ContainsFold predicate on the "location" field.
func LocationContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldLocation, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldURL, v))
}

// MeetingURLEQ applies the EQ predicate on the "meeting_url" field.
func MeetingURLEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldMeetingURL, v))
}

// MeetingURLNEQ applies the NEQ predicate on the "meeting_url" field.
func MeetingURLNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldMeetingURL, v))
}

// MeetingURLIn applies the In predicate on the "meeting_url" field.
func MeetingURLIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldMeetingURL, vs...))
}

// MeetingURLNotIn applies the NotIn predicate on the "meeting_url" field.
func MeetingURLNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldMeetingURL, vs...))
}

// MeetingURLGT applies the GT predicate on the "meeting_url" field.
func MeetingURLGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldMeetingURL, v))
}

// MeetingURLGTE applies the GTE predicate on the "meeting_url" field.
func MeetingURLGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldMeetingURL, v))
}

// MeetingURLLT applies the LT predicate on the "meeting_url" field.
func MeetingURLLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldMeetingURL, v))
}

// MeetingURLLTE applies the LTE predicate on the "meeting_url" field.
func MeetingURLLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldMeetingURL, v))
}

// MeetingURLContains applies the Contains predicate on the "meeting_url" field.
func MeetingURLContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldMeetingURL, v))
}

// MeetingURLHasPrefix applies the HasPrefix predicate on the "meeting_url" field.
func MeetingURLHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldMeetingURL, v))
}

// MeetingURLHasSuffix applies the HasSuffix predicate on the "meeting_url" field.
func MeetingURLHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldMeetingURL, v))
}

// MeetingURLIsNil applies the IsNil predicate on the "meeting_url" field.
func MeetingURLIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldMeetingURL))
}

// MeetingURLNotNil applies the NotNil predicate on the "meeting_url" field.
func MeetingURLNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldMeetingURL))
}

// MeetingURLEqualFold applies the EqualFold predicate on the "meeting_url" field.
func MeetingURLEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldMeetingURL, v))
}

// MeetingURLContainsFold applies the ContainsFold predicate on the "meeting_url" field.
func MeetingURLContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldMeetingURL, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldStatus, vs...))
}

// StartEQ applies the EQ predicate on the "start" field.
func StartEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldStart, v))
}

// StartNEQ applies the NEQ predicate on the "start" field.
func StartNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldStart, v))
}

// StartIn applies the In predicate on the "start" field.
func StartIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldStart, vs...))
}

// StartNotIn applies the NotIn predicate on the "start" field.
func StartNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldStart, vs...))
}

// StartGT applies the GT predicate on the "start" field.
func StartGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldStart, v))
}

// StartGTE applies the GTE predicate on the "start" field.
func StartGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldStart, v))
}

// StartLT applies the LT predicate on the "start" field.
func StartLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldStart, v))
}

// StartLTE applies the LTE predicate on the "start" field.
func StartLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldStart, v))
}

// EndEQ applies the EQ predicate on the "end" field.
func EndEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldEnd, v))
}

// EndNEQ applies the NEQ predicate on the "end" field.
func EndNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldEnd, v))
}

// EndIn applies the In predicate on the "end" field.
func EndIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldEnd, vs...))
}

// EndNotIn applies the NotIn predicate on the "end" field.
func EndNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldEnd, vs...))
}

// EndGT applies the GT predicate on the "end" field.
func EndGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldEnd, v))
}

// EndGTE applies the GTE predicate on the "end" field.
func EndGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldEnd, v))
}

// EndLT applies the LT predicate on the "end" field.
func EndLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldEnd, v))
}

// EndLTE applies the LTE predicate on the "end" field.
func EndLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldEnd, v))
}

// AllDayEQ applies the EQ predicate on the "all_day" field.
func AllDayEQ(v bool) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldAllDay, v))
}

// AllDayNEQ applies the NEQ predicate on the "all_day" field.
func AllDayNEQ(v bool) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldAllDay, v))
}

// StartTzEQ applies the EQ predicate on the "start_tz" field.
func StartTzEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldStartTz, v))
}

// StartTzNEQ applies the NEQ predicate on the "start_tz" field.
func StartTzNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldStartTz, v))
}

// StartTzIn applies the In predicate on the "start_tz" field.
func StartTzIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldStartTz, vs...))
}

// StartTzNotIn applies the NotIn predicate on the "start_tz" field.
func StartTzNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldStartTz, vs...))
}

// StartTzGT applies the GT predicate on the "start_tz" field.
func StartTzGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldStartTz, v))
}

// StartTzGTE applies the GTE predicate on the "start_tz" field.
func StartTzGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldStartTz, v))
}

// StartTzLT applies the LT predicate on the "start_tz" field.
func StartTzLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldStartTz, v))
}

// StartTzLTE applies the LTE predicate on the "start_tz" field.
func StartTzLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldStartTz, v))
}

// StartTzContains applies the Contains predicate on the "start_tz" field.
func StartTzContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldStartTz, v))
}

// StartTzHasPrefix applies the HasPrefix predicate on the "start_tz" field.
func StartTzHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldStartTz, v))
}

// StartTzHasSuffix applies the HasSuffix predicate on the "start_tz" field.
func StartTzHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldStartTz, v))
}

// StartTzIsNil applies the IsNil predicate on the "start_tz" field.
func StartTzIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldStartTz))
}

// StartTzNotNil applies the NotNil predicate on the "start_tz" field.
func StartTzNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldStartTz))
}

// StartTzEqualFold applies the EqualFold predicate on the "start_tz" field.
func StartTzEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldStartTz, v))
}

// StartTzContainsFold applies the ContainsFold predicate on the "start_tz" field.
func StartTzContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldStartTz, v))
}

// EndTzEQ applies the EQ predicate on the "end_tz" field.
func EndTzEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldEndTz, v))
}

// EndTzNEQ applies the NEQ predicate on the "end_tz" field.
func EndTzNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldEndTz, v))
}

// EndTzIn applies the In predicate on the "end_tz" field.
func EndTzIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldEndTz, vs...))
}

// EndTzNotIn applies the NotIn predicate on the "end_tz" field.
func EndTzNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldEndTz, vs...))
}

// EndTzGT applies the GT predicate on the "end_tz" field.
func EndTzGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldEndTz, v))
}

// EndTzGTE applies the GTE predicate on the "end_tz" field.
func EndTzGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldEndTz, v))
}

// EndTzLT applies the LT predicate on the "end_tz" field.
func EndTzLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldEndTz, v))
}

// EndTzLTE applies the LTE predicate on the "end_tz" field.
func EndTzLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldEndTz, v))
}

// EndTzContains applies the Contains predicate on the "end_tz" field.
func EndTzContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldEndTz, v))
}

// EndTzHasPrefix applies the HasPrefix predicate on the "end_tz" field.
func EndTzHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldEndTz, v))
}

// EndTzHasSuffix applies the HasSuffix predicate on the "end_tz" field.
func EndTzHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldEndTz, v))
}

// EndTzIsNil applies the IsNil predicate on the "end_tz" field.
func EndTzIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldEndTz))
}

// EndTzNotNil applies the NotNil predicate on the "end_tz" field.
func EndTzNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldEndTz))
}

// EndTzEqualFold applies the EqualFold predicate on the "end_tz" field.
func EndTzEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldEndTz, v))
}

// EndTzContainsFold applies the ContainsFold predicate on the "end_tz" field.
func EndTzContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldEndTz, v))
}

// RecurrenceIsNil applies the IsNil predicate on the "recurrence" field.
func RecurrenceIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldRecurrence))
}

// RecurrenceNotNil applies the NotNil predicate on the "recurrence" field.
func RecurrenceNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldRecurrence))
}

// RecurringIDEQ applies the EQ predicate on the "recurring_id" field.
func RecurringIDEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRecurringID, v))
}

// RecurringIDNEQ applies the NEQ predicate on the "recurring_id" field.
func RecurringIDNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldRecurringID, v))
}

// RecurringIDIn applies the In predicate on the "recurring_id" field.
func RecurringIDIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldRecurringID, vs...))
}

// RecurringIDNotIn applies the NotIn predicate on the "recurring_id" field.
func RecurringIDNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldRecurringID, vs...))
}

// RecurringIDGT applies the GT predicate on the "recurring_id" field.
func RecurringIDGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldRecurringID, v))
}

// RecurringIDGTE applies the GTE predicate on the "recurring_id" field.
func RecurringIDGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldRecurringID, v))
}

// RecurringIDLT applies the LT predicate on the "recurring_id" field.
func RecurringIDLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldRecurringID, v))
}

// RecurringIDLTE applies the LTE predicate on the "recurring_id" field.
func RecurringIDLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldRecurringID, v))
}

// RecurringIDContains applies the Contains predicate on the "recurring_id" field.
func RecurringIDContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldRecurringID, v))
}

// RecurringIDHasPrefix applies the HasPrefix predicate on the "recurring_id" field.
func RecurringIDHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldRecurringID, v))
}

// RecurringIDHasSuffix applies the HasSuffix predicate on the "recurring_id" field.
func RecurringIDHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldRecurringID, v))
}

// RecurringIDIsNil applies the IsNil predicate on the "recurring_id" field.
func RecurringIDIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldRecurringID))
}

// RecurringIDNotNil applies the NotNil predicate on the "recurring_id" field.
func RecurringIDNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldRecurringID))
}

// RecurringIDEqualFold applies the EqualFold predicate on the "recurring_id" field.
func RecurringIDEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldRecurringID, v))
}

// RecurringIDContainsFold applies the ContainsFold predicate on the "recurring_id" field.
func RecurringIDContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldRecurringID, v))
}

// OriginalStartEQ applies the EQ predicate on the "original_start" field.
func OriginalStartEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldOriginalStart, v))
}

// OriginalStartNEQ applies the NEQ predicate on the "original_start" field.
func OriginalStartNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldOriginalStart, v))
}

// OriginalStartIn applies the In predicate on the "original_start" field.
func OriginalStartIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldOriginalStart, vs...))
}

// OriginalStartNotIn applies the NotIn predicate on the "original_start" field.
func OriginalStartNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldOriginalStart, vs...))
}

// OriginalStartGT applies the GT predicate on the "original_start" field.
func OriginalStartGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldOriginalStart, v))
}

// OriginalStartGTE applies the GTE predicate on the "original_start" field.
func OriginalStartGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldOriginalStart, v))
}

// OriginalStartLT applies the LT predicate on the "original_start" field.
func OriginalStartLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldOriginalStart, v))
}

// OriginalStartLTE applies the LTE predicate on the "original_start" field.
func OriginalStartLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldOriginalStart, v))
}

// OriginalStartIsNil applies the IsNil predicate on the "original_start" field.
func OriginalStartIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldOriginalStart))
}

// OriginalStartNotNil applies the NotNil predicate on the "original_start" field.
func OriginalStartNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldOriginalStart))
}

// OrganizerIsNil applies the IsNil predicate on the "organizer" field.
func OrganizerIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldOrganizer))
}

// OrganizerNotNil applies the NotNil predicate on the "organizer" field.
func OrganizerNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldOrganizer))
}

// AttendeesIsNil applies the IsNil predicate on the "attendees" field.
func AttendeesIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldAttendees))
}

// AttendeesNotNil applies the NotNil predicate on the "attendees" field.
func AttendeesNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldAttendees))
}

// RemindersIsNil applies the IsNil predicate on the "reminders" field.
func RemindersIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldReminders))
}

// RemindersNotNil applies the NotNil predicate on the "reminders" field.
func RemindersNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldReminders))
}

// CategoriesIsNil applies the IsNil predicate on the "categories" field.
func CategoriesIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldCategories))
}

// CategoriesNotNil applies the NotNil predicate on the "categories" field.
func CategoriesNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldCategories))
}

// TransparencyEQ applies the EQ predicate on the "transparency" field.
func TransparencyEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldTransparency, v))
}

// TransparencyNEQ applies the NEQ predicate on the "transparency" field.
func TransparencyNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldTransparency, v))
}

// TransparencyIn applies the In predicate on the "transparency" field.
func TransparencyIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldTransparency, vs...))
}

// TransparencyNotIn applies the NotIn predicate on the "transparency" field.
func TransparencyNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldTransparency, vs...))
}

// TransparencyGT applies the GT predicate on the "transparency" field.
func TransparencyGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldTransparency, v))
}

// TransparencyGTE applies the GTE predicate on the "transparency" field.
func TransparencyGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldTransparency, v))
}

// TransparencyLT applies the LT predicate on the "transparency" field.
func TransparencyLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldTransparency, v))
}

// TransparencyLTE applies the LTE predicate on the "transparency" field.
func TransparencyLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldTransparency, v))
}

// TransparencyContains applies the Contains predicate on the "transparency" field.
func TransparencyContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldTransparency, v))
}

// TransparencyHasPrefix applies the HasPrefix predicate on the "transparency" field.
func TransparencyHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldTransparency, v))
}

// TransparencyHasSuffix applies the HasSuffix predicate on the "transparency" field.
func TransparencyHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldTransparency, v))
}

// TransparencyIsNil applies the IsNil predicate on the "transparency" field.
func TransparencyIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldTransparency))
}

// TransparencyNotNil applies the NotNil predicate on the "transparency" field.
func TransparencyNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldTransparency))
}

// TransparencyEqualFold applies the EqualFold predicate on the "transparency" field.
func TransparencyEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldTransparency, v))
}

// TransparencyContainsFold applies the ContainsFold predicate on the "transparency" field.
func TransparencyContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldTransparency, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldVisibility, vs...))
}

// VisibilityGT applies the GT predicate on the "visibility" field.
func VisibilityGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldVisibility, v))
}

// VisibilityGTE applies the GTE predicate on the "visibility" field.
func VisibilityGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldVisibility, v))
}

// VisibilityLT applies the LT predicate on the "visibility" field.
func VisibilityLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldVisibility, v))
}

// VisibilityLTE applies the LTE predicate on the "visibility" field.
func VisibilityLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldVisibility, v))
}

// VisibilityContains applies the Contains predicate on the "visibility" field.
func VisibilityContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldVisibility, v))
}

// VisibilityHasPrefix applies the HasPrefix predicate on the "visibility" field.
func VisibilityHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldVisibility, v))
}

// VisibilityHasSuffix applies the HasSuffix predicate on the "visibility" field.
func VisibilityHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldVisibility, v))
}

// VisibilityIsNil applies the IsNil predicate on the "visibility" field.
func VisibilityIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldVisibility))
}

// VisibilityNotNil applies the NotNil predicate on the "visibility" field.
func VisibilityNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldVisibility))
}

// VisibilityEqualFold applies the EqualFold predicate on the "visibility" field.
func VisibilityEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldVisibility, v))
}

// VisibilityContainsFold applies the ContainsFold predicate on the "visibility" field.
func VisibilityContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldVisibility, v))
}

// CrmRefEQ applies the EQ predicate on the "crm_ref" field.
func CrmRefEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCrmRef, v))
}

// CrmRefNEQ applies the NEQ predicate on the "crm_ref" field.
func CrmRefNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCrmRef, v))
}

// CrmRefIn applies the In predicate on the "crm_ref" field.
func CrmRefIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCrmRef, vs...))
}

// CrmRefNotIn applies the NotIn predicate on the "crm_ref" field.
func CrmRefNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCrmRef, vs...))
}

// CrmRefGT applies the GT predicate on the "crm_ref" field.
func CrmRefGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCrmRef, v))
}

// CrmRefGTE applies the GTE predicate on the "crm_ref" field.
func CrmRefGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCrmRef, v))
}

// CrmRefLT applies the LT predicate on the "crm_ref" field.
func CrmRefLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCrmRef, v))
}

// CrmRefLTE applies the LTE predicate on the "crm_ref" field.
func CrmRefLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCrmRef, v))
}

// CrmRefContains applies the Contains predicate on the "crm_ref" field.
func CrmRefContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldCrmRef, v))
}

// CrmRefHasPrefix applies the HasPrefix predicate on the "crm_ref" field.
func CrmRefHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldCrmRef, v))
}

// CrmRefHasSuffix applies the HasSuffix predicate on the "crm_ref" field.
func CrmRefHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldCrmRef, v))
}

// CrmRefIsNil applies the IsNil predicate on the "crm_ref" field.
func CrmRefIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldCrmRef))
}

// CrmRefNotNil applies the NotNil predicate on the "crm_ref" field.
func CrmRefNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldCrmRef))
}

// CrmRefEqualFold applies the EqualFold predicate on the "crm_ref" field.
func CrmRefEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldCrmRef, v))
}

// CrmRefContainsFold applies the ContainsFold predicate on the "crm_ref" field.
func CrmRefContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldCrmRef, v))
}

// CrmKindEQ applies the EQ predicate on the "crm_kind" field.
func CrmKindEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCrmKind, v))
}

// CrmKindNEQ applies the NEQ predicate on the "crm_kind" field.
func CrmKindNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCrmKind, v))
}

// CrmKindIn applies the In predicate on the "crm_kind" field.
func CrmKindIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCrmKind, vs...))
}

// CrmKindNotIn applies the NotIn predicate on the "crm_kind" field.
func CrmKindNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCrmKind, vs...))
}

// CrmKindGT applies the GT predicate on the "crm_kind" field.
func CrmKindGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCrmKind, v))
}

// CrmKindGTE applies the GTE predicate on the "crm_kind" field.
func CrmKindGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCrmKind, v))
}

// CrmKindLT applies the LT predicate on the "crm_kind" field.
func CrmKindLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCrmKind, v))
}

// CrmKindLTE applies the LTE predicate on the "crm_kind" field.
func CrmKindLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCrmKind, v))
}

// CrmKindContains applies the Contains predicate on the "crm_kind" field.
func CrmKindContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldCrmKind, v))
}

// CrmKindHasPrefix applies the HasPrefix predicate on the "crm_kind" field.
func CrmKindHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldCrmKind, v))
}

// CrmKindHasSuffix applies the HasSuffix predicate on the "crm_kind" field.
func CrmKindHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldCrmKind, v))
}

// CrmKindIsNil applies the IsNil predicate on the "crm_kind" field.
func CrmKindIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldCrmKind))
}

// CrmKindNotNil applies the NotNil predicate on the "crm_kind" field.
func CrmKindNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldCrmKind))
}

// CrmKindEqualFold applies the EqualFold predicate on the "crm_kind" field.
func CrmKindEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldCrmKind, v))
}

// CrmKindContainsFold applies the ContainsFold predicate on the "crm_kind" field.
func CrmKindContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldCrmKind, v))
}

// RawIcsEQ applies the EQ predicate on the "raw_ics" field.
func RawIcsEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRawIcs, v))
}

// RawIcsNEQ applies the NEQ predicate on the "raw_ics" field.
func RawIcsNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldRawIcs, v))
}

// RawIcsIn applies the In predicate on the "raw_ics" field.
func RawIcsIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldRawIcs, vs...))
}

// RawIcsNotIn applies the NotIn predicate on the "raw_ics" field.
func RawIcsNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldRawIcs, vs...))
}

// RawIcsGT applies the GT predicate on the "raw_ics" field.
func RawIcsGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldRawIcs, v))
}

// RawIcsGTE applies the GTE predicate on the "raw_ics" field.
func RawIcsGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldRawIcs, v))
}

// RawIcsLT applies the LT predicate on the "raw_ics" field.
func RawIcsLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldRawIcs, v))
}

// RawIcsLTE applies the LTE predicate on the "raw_ics" field.
func RawIcsLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldRawIcs, v))
}

// RawIcsContains applies the Contains predicate on the "raw_ics" field.
func RawIcsContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldRawIcs, v))
}

// RawIcsHasPrefix applies the HasPrefix predicate on the "raw_ics" field.
func RawIcsHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldRawIcs, v))
}

// RawIcsHasSuffix applies the HasSuffix predicate on the "raw_ics" field.
func RawIcsHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldRawIcs, v))
}

// RawIcsIsNil applies the IsNil predicate on the "raw_ics" field.
func RawIcsIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldRawIcs))
}

// RawIcsNotNil applies the NotNil predicate on the "raw_ics" field.
func RawIcsNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldRawIcs))
}

// RawIcsEqualFold applies the EqualFold predicate on the "raw_ics" field.
func RawIcsEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldRawIcs, v))
}

// RawIcsContainsFold applies the ContainsFold predicate on the "raw_ics" field.
func RawIcsContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldRawIcs, v))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCreated, v))
}

// UpdatedEQ applies the EQ predicate on the "updated" field.
func UpdatedEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUpdated, v))
}

// UpdatedNEQ applies the NEQ predicate on the "updated" field.
func UpdatedNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldUpdated, v))
}

// UpdatedIn applies the In predicate on the "updated" field.
func UpdatedIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldUpdated, vs...))
}

// UpdatedNotIn applies the NotIn predicate on the "updated" field.
func UpdatedNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldUpdated, vs...))
}

// UpdatedGT applies the GT predicate on the "updated" field.
func UpdatedGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldUpdated, v))
}

// UpdatedGTE applies the GTE predicate on the "updated" field.
func UpdatedGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldUpdated, v))
}

// UpdatedLT applies the LT predicate on the "updated" field.
func UpdatedLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldUpdated, v))
}

// UpdatedLTE applies the LTE predicate on the "updated" field.
func UpdatedLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldUpdated, v))
}

// HasCalendar applies the HasEdge predicate on the "calendar" edge.
func HasCalendar() predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CalendarTable, CalendarColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCalendarWith applies the HasEdge predicate on the "calendar" edge with a given conditions (other predicates).
func HasCalendarWith(preds ...predicate.Calendar) predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := newCalendarStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Event) predicate.Event {
	return predicate.Event(sql.NotPredicates(p))
}
