[[entry]]
played_at = "2026-08-18T10:37:51Z"
path = "/mnt/nas/music/ABBA/Gold_ Greatest Hits/01 Dancing Queen.m4a"
title = "Dancing Queen"
artist = "ABBA"
album = "Gold: Greatest Hits"
genre = "Rock"
year = 1992
track_number = 1
