[[entry]]
played_at = "2026-08-19T08:56:46Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=FTbLmDO8qWl82VbCtuSN7M&s=83ecfd535fe92c4e&t=263778dd1ffa2cc61ec2728f129da6a8&u=mecattaf&v=1.0.0"
title = "Leaves"
artist = "Parcels"
album = "LOVED"
genre = "Alternative"
year = 2025
duration_secs = 221

[[entry]]
played_at = "2026-08-19T08:53:05Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=QKrNnJGCEd9cKClKfu1f6l&s=209f40d4989d3be6&t=1b2e0945e374b48334863d567369754a&u=mecattaf&v=1.0.0"
title = "Yougotmefeeling"
artist = "Parcels"
album = "Yougotmefeeling"
genre = "Pop"
year = 2025
duration_secs = 183

[[entry]]
played_at = "2026-08-19T08:50:02Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=kFTMa2QzAlIQgUjFE1n01x&s=26822f1ea91b565c&t=765e5cd944b505f27c10e8ac44e7ec90&u=mecattaf&v=1.0.0"
title = "Sorry"
artist = "Parcels"
album = "Sorry"
genre = "Alternative"
year = 2025
duration_secs = 197

[[entry]]
played_at = "2026-08-19T08:46:44Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=yFm96qzcNPb9fd3tzZj6My&s=b1efe3bea743612d&t=70abcfc9928626c942ffe7ea38dc1a2b&u=mecattaf&v=1.0.0"
title = "Safeandsound"
artist = "Parcels"
album = "Safeandsound"
genre = "Alternative"
year = 2025
duration_secs = 277

[[entry]]
played_at = "2026-08-19T08:42:07Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=mKlhFKnbeO3OqkvugODzf1&s=87f93d5566bb357f&t=a5440c2d1aab6863111e48b0eeff0d7b&u=mecattaf&v=1.0.0"
title = "Ifyoucall"
artist = "Parcels"
album = "LOVED"
genre = "Alternative"
year = 2025
duration_secs = 241

[[entry]]
played_at = "2026-08-19T08:37:31Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=w4xvj24ReLcjdbDvpCzU44&s=c6ee710a840823f0&t=6d91bc9a6ccc67d3f962957aacc5ddd8&u=mecattaf&v=1.0.0"
title = "Living Together, Growing Together"
artist = "Burt Bacharach"
album = "Living Together"
genre = "Pop"
year = 2020
duration_secs = 246

[[entry]]
played_at = "2026-08-19T08:33:25Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=86H4h0lwfDPPk2s5MgrmC1&s=3f9235e6836f0999&t=30210cdb633ebcb7d471710105a8f581&u=mecattaf&v=1.0.0"
title = "Wives And Lovers"
artist = "Burt Bacharach"
album = "Wives and Lovers"
genre = "Pop"
year = 2015
duration_secs = 172

[[entry]]
played_at = "2026-08-19T08:30:33Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=bAisfl97re6Zfg3EANCG0P&s=40cdeef732fee7df&t=51597321b213e922771c3f160d2d5b39&u=mecattaf&v=1.0.0"
title = "A House Is Not A Home"
artist = "Burt Bacharach"
album = "Reach Out"
genre = "Easy Listening"
year = 2018
duration_secs = 228

[[entry]]
played_at = "2026-08-19T08:26:44Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=B8foR2PqbkZBhaSOUYrqaB&s=3eefd457780dd3a2&t=a0a7426a92586fe041fec452df6f5fdf&u=mecattaf&v=1.0.0"
title = "Pacific Coast Highway"
artist = "Burt Bacharach"
album = "Make It Easy On Yourself"
genre = "Vocal"
year = 2018
duration_secs = 202

[[entry]]
played_at = "2026-08-19T08:23:22Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=WA7lXBY5bP6t0NgAy3dE6A&s=77f128429100790e&t=7077a9781e750fee1ca145e21b131253&u=mecattaf&v=1.0.0"
title = "Any Day Now"
artist = "Burt Bacharach"
album = "What The World Needs Now: Burt Bacharach Classics"
genre = "Vocal"
year = 2018
duration_secs = 203

[[entry]]
played_at = "2026-08-19T08:19:49Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=voZHaOhuWITZQ5bdwB3JnD&s=567c9192ff31fad7&t=05515ac335fbac3a3a20f57278e1a96a&u=mecattaf&v=1.0.0"
title = "(They Long to Be) Close to You"
artist = "Burt Bacharach"
album = "Burt Bacharach"
genre = "Vocal"
year = 2018
duration_secs = 198

[[entry]]
played_at = "2026-08-19T08:16:17Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=pChrLZaNPDS5mA9n9tMRUb&s=e91e42849ec64513&t=c0f87591cc957d2a522a24a5bc3eac20&u=mecattaf&v=1.0.0"
title = "Burt Bacharach / Hal David ~ Promises, Promises"
artist = "NewMediaFormat / TheNewFormat"
album = "[Unknown Album]"
genre = "Pop"
year = 2010
duration_secs = 172

[[entry]]
played_at = "2026-08-19T07:49:56Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=LHNwyMQcY6oFOt5iD0jJRG&s=033ae7cc74925003&t=86203b0d48e542178fc520167475473c&u=mecattaf&v=1.0.0"
title = "Rave & Love w/ DSM - 02.06.21"
artist = "interval"
album = "[Unknown Album]"
genre = "Electronic"
year = 2021
duration_secs = 3508

[[entry]]
played_at = "2026-08-19T07:49:56Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=v81BPThHpovKJx8t9NxQYP&s=7a71243661968dc9&t=23d2add15b43e7ce64711edfa038eaa7&u=mecattaf&v=1.0.0"
title = "Rave & Love w/ DSM \u200b- 07.07.21"
artist = "TAYLOR"
album = "[Unknown Album]"
year = 2021
duration_secs = 3501

[[entry]]
played_at = "2026-08-19T07:49:54Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=2B0u7nnKgQb9Qv8bhZLq4u&s=93fa6218f2a63555&t=829cc5a004a02a54bdb3e1a4b75bcbda&u=mecattaf&v=1.0.0"
title = "📻 Radio Show @ Voices London 📻 World, Funk, Disco..."
artist = "DSM"
album = "[Unknown Album]"
genre = "World"
year = 2021
duration_secs = 6879

[[entry]]
played_at = "2026-08-18T17:21:35Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=92P4SXBIF3M3qxmQjGhYe2&s=11a29f7ce9551ee3&t=d69d8ce721eb1f52a7d20c7db7d6d7c1&u=mecattaf&v=1.0.0"
title = "North"
artist = "Phoenix"
album = "It's Never Been Like That"
genre = "Pop"
year = 2014
duration_secs = 301

[[entry]]
played_at = "2026-08-18T17:16:33Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=MEYnqpnWcqtWDFejy6Qr6I&s=fc1b096abeeede4e&t=ca5b81b07427ce2564db8fd30c9f166d&u=mecattaf&v=1.0.0"
title = "Courtesy Laughs"
artist = "Phoenix"
album = "It's Never Been Like That"
genre = "Pop"
year = 2014
duration_secs = 194

[[entry]]
played_at = "2026-08-18T17:13:19Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=o8r3XRhkFQ5rGw2ngg124y&s=590e250dae68b16d&t=38fbbc30294920a0372107783e7cedb2&u=mecattaf&v=1.0.0"
title = "Lost and Found"
artist = "Phoenix"
album = "It's Never Been Like That"
genre = "Pop"
year = 2014
duration_secs = 176

[[entry]]
played_at = "2026-08-18T17:10:22Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=4tKwFBdDpHegvoxxS0z0tk&s=976e4830abbbe334&t=06d957d9ababfe64ebe223d2f8761fb1&u=mecattaf&v=1.0.0"
title = "One Time Too Many"
artist = "Phoenix"
album = "It's Never Been Like That"
genre = "Pop"
year = 2014
duration_secs = 220

[[entry]]
played_at = "2026-08-18T17:06:42Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=iIieVFbaphdoJ9POgAQDE7&s=78b5561acbdf6415&t=3cc40176a155dd49bc7ad3904e49af04&u=mecattaf&v=1.0.0"
title = "Long Distance Call"
artist = "Phoenix"
album = "Long Distance Call"
genre = "Pop"
year = 2016
duration_secs = 186

[[entry]]
played_at = "2026-08-18T17:03:35Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=TywtTnYk5ecuJldAoGm3ia&s=5b0ff0bc5dfae117&t=363342d330f84fc240a3bb3e23ca9d42&u=mecattaf&v=1.0.0"
title = "Phoenix - Rally"
artist = "welovephoenix"
album = "[Unknown Album]"
genre = "Rock"
year = 2009
duration_secs = 197

[[entry]]
played_at = "2026-08-18T16:59:08Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=hCbgvFXUOIMeFRKghZhhD2&s=ac3218a4f4bdea80&t=5b3c2be594b2e0144fe0efacaa2a26d5&u=mecattaf&v=1.0.0"
title = "Gurenge but is it okay if it's lofi?"
artist = "Kijugo"
album = "[Unknown Album]"
genre = "Lofi"
year = 2021
duration_secs = 198

[[entry]]
played_at = "2026-08-18T16:57:16Z"
path = "http://coordinator.tail8dd1.ts.net:4533/rest/stream?c=cliamp&f=json&format=raw&id=2d8Tnu4e0EXHSvnPmhUIix&s=6fe3b15b13a92e7c&t=557bcd3fc6424738fe2dcea1bc6902d1&u=mecattaf&v=1.0.0"
title = "Unravel but is it okay if it's lofi?"
artist = "Kijugo"
album = "[Unknown Album]"
genre = "Lofi"
year = 2020
duration_secs = 155

[[entry]]
played_at = "2026-08-18T10:37:51Z"
path = "/mnt/nas/music/ABBA/Gold_ Greatest Hits/01 Dancing Queen.m4a"
title = "Dancing Queen"
artist = "ABBA"
album = "Gold: Greatest Hits"
genre = "Rock"
year = 1992
track_number = 1
