// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mecattaf/dcal/ent/account"
	"github.com/mecattaf/dcal/ent/calendar"
	"github.com/mecattaf/dcal/ent/secret"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKind sets the "kind" field.
func (_c *AccountCreate) SetKind(v account.Kind) *AccountCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *AccountCreate) SetDisplayName(v string) *AccountCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetSettings sets the "settings" field.
func (_c *AccountCreate) SetSettings(v map[string]interface{}) *AccountCreate {
	_c.mutation.SetSettings(v)
	return _c
}

// SetNeedsReauth sets the "needs_reauth" field.
func (_c *AccountCreate) SetNeedsReauth(v bool) *AccountCreate {
	_c.mutation.SetNeedsReauth(v)
	return _c
}

// SetNillableNeedsReauth sets the "needs_reauth" field if the given value is not nil.
func (_c *AccountCreate) SetNillableNeedsReauth(v *bool) *AccountCreate {
	if v != nil {
		_c.SetNeedsReauth(*v)
	}
	return _c
}

// SetAuthError sets the "auth_error" field.
func (_c *AccountCreate) SetAuthError(v string) *AccountCreate {
	_c.mutation.SetAuthError(v)
	return _c
}

// SetNillableAuthError sets the "auth_error" field if the given value is not nil.
func (_c *AccountCreate) SetNillableAuthError(v *string) *AccountCreate {
	if v != nil {
		_c.SetAuthError(*v)
	}
	return _c
}

// SetSyncNotice sets the "sync_notice" field.
func (_c *AccountCreate) SetSyncNotice(v string) *AccountCreate {
	_c.mutation.SetSyncNotice(v)
	return _c
}

// SetNillableSyncNotice sets the "sync_notice" field if the given value is not nil.
func (_c *AccountCreate) SetNillableSyncNotice(v *string) *AccountCreate {
	if v != nil {
		_c.SetSyncNotice(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountCreate) SetCreatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableCreatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountCreate) SetUpdatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableUpdatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccountCreate) SetID(v string) *AccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddCalendarIDs adds the "calendars" edge to the Calendar entity by IDs.
func (_c *AccountCreate) AddCalendarIDs(ids ...string) *AccountCreate {
	_c.mutation.AddCalendarIDs(ids...)
	return _c
}

// AddCalendars adds the "calendars" edges to the Calendar entity.
func (_c *AccountCreate) AddCalendars(v ...*Calendar) *AccountCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCalendarIDs(ids...)
}

// AddSecretIDs adds the "secrets" edge to the Secret entity by IDs.
func (_c *AccountCreate) AddSecretIDs(ids ...string) *AccountCreate {
	_c.mutation.AddSecretIDs(ids...)
	return _c
}

// AddSecrets adds the "secrets" edges to the Secret entity.
func (_c *AccountCreate) AddSecrets(v ...*Secret) *AccountCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSecretIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_c *AccountCreate) Mutation() *AccountMutation {
	return _c.mutation
}

// Save creates the Account in the database.
func (_c *AccountCreate) Save(ctx context.Context) (*Account, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCreate) defaults() {
	if _, ok := _c.mutation.NeedsReauth(); !ok {
		v := account.DefaultNeedsReauth
		_c.mutation.SetNeedsReauth(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := account.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := account.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Account.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := account.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Account.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "Account.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := account.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Account.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NeedsReauth(); !ok {
		return &ValidationError{Name: "needs_reauth", err: errors.New(`ent: missing required field "Account.needs_reauth"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Account.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Account.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := account.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Account.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Account.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(account.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(account.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Settings(); ok {
		_spec.SetField(account.FieldSettings, field.TypeJSON, value)
		_node.Settings = value
	}
	if value, ok := _c.mutation.NeedsReauth(); ok {
		_spec.SetField(account.FieldNeedsReauth, field.TypeBool, value)
		_node.NeedsReauth = value
	}
	if value, ok := _c.mutation.AuthError(); ok {
		_spec.SetField(account.FieldAuthError, field.TypeString, value)
		_node.AuthError = value
	}
	if value, ok := _c.mutation.SyncNotice(); ok {
		_spec.SetField(account.FieldSyncNotice, field.TypeString, value)
		_node.SyncNotice = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CalendarsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.CalendarsTable,
			Columns: []string{account.CalendarsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendar.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SecretsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SecretsTable,
			Columns: []string{account.SecretsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secret.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.Create().
//		SetKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCreate) OnConflict(opts ...sql.ConflictOption) *AccountUpsertOne {
	_c.conflict = opts
	return &AccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCreate) OnConflictColumns(columns ...string) *AccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertOne{
		create: _c,
	}
}

type (
	// AccountUpsertOne is the builder for "upsert"-ing
	//  one Account node.
	AccountUpsertOne struct {
		create *AccountCreate
	}

	// AccountUpsert is the "OnConflict" setter.
	AccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetDisplayName sets the "display_name" field.
func (u *AccountUpsert) SetDisplayName(v string) *AccountUpsert {
	u.Set(account.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AccountUpsert) UpdateDisplayName() *AccountUpsert {
	u.SetExcluded(account.FieldDisplayName)
	return u
}

// SetSettings sets the "settings" field.
func (u *AccountUpsert) SetSettings(v map[string]interface{}) *AccountUpsert {
	u.Set(account.FieldSettings, v)
	return u
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *AccountUpsert) UpdateSettings() *AccountUpsert {
	u.SetExcluded(account.FieldSettings)
	return u
}

// ClearSettings clears the value of the "settings" field.
func (u *AccountUpsert) ClearSettings() *AccountUpsert {
	u.SetNull(account.FieldSettings)
	return u
}

// SetNeedsReauth sets the "needs_reauth" field.
func (u *AccountUpsert) SetNeedsReauth(v bool) *AccountUpsert {
	u.Set(account.FieldNeedsReauth, v)
	return u
}

// UpdateNeedsReauth sets the "needs_reauth" field to the value that was provided on create.
func (u *AccountUpsert) UpdateNeedsReauth() *AccountUpsert {
	u.SetExcluded(account.FieldNeedsReauth)
	return u
}

// SetAuthError sets the "auth_error" field.
func (u *AccountUpsert) SetAuthError(v string) *AccountUpsert {
	u.Set(account.FieldAuthError, v)
	return u
}

// UpdateAuthError sets the "auth_error" field to the value that was provided on create.
func (u *AccountUpsert) UpdateAuthError() *AccountUpsert {
	u.SetExcluded(account.FieldAuthError)
	return u
}

// ClearAuthError clears the value of the "auth_error" field.
func (u *AccountUpsert) ClearAuthError() *AccountUpsert {
	u.SetNull(account.FieldAuthError)
	return u
}

// SetSyncNotice sets the "sync_notice" field.
func (u *AccountUpsert) SetSyncNotice(v string) *AccountUpsert {
	u.Set(account.FieldSyncNotice, v)
	return u
}

// UpdateSyncNotice sets the "sync_notice" field to the value that was provided on create.
func (u *AccountUpsert) UpdateSyncNotice() *AccountUpsert {
	u.SetExcluded(account.FieldSyncNotice)
	return u
}

// ClearSyncNotice clears the value of the "sync_notice" field.
func (u *AccountUpsert) ClearSyncNotice() *AccountUpsert {
	u.SetNull(account.FieldSyncNotice)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsert) SetUpdatedAt(v time.Time) *AccountUpsert {
	u.Set(account.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsert) UpdateUpdatedAt() *AccountUpsert {
	u.SetExcluded(account.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(account.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountUpsertOne) UpdateNewValues() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(account.FieldID)
		}
		if _, exists := u.create.mutation.Kind(); exists {
			s.SetIgnore(account.FieldKind)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(account.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUpsertOne) Ignore() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertOne) DoNothing() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreate.OnConflict
// documentation for more info.
func (u *AccountUpsertOne) Update(set func(*AccountUpsert)) *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *AccountUpsertOne) SetDisplayName(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateDisplayName() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateDisplayName()
	})
}

// SetSettings sets the "settings" field.
func (u *AccountUpsertOne) SetSettings(v map[string]interface{}) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateSettings() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSettings()
	})
}

// ClearSettings clears the value of the "settings" field.
func (u *AccountUpsertOne) ClearSettings() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.ClearSettings()
	})
}

// SetNeedsReauth sets the "needs_reauth" field.
func (u *AccountUpsertOne) SetNeedsReauth(v bool) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetNeedsReauth(v)
	})
}

// UpdateNeedsReauth sets the "needs_reauth" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateNeedsReauth() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateNeedsReauth()
	})
}

// SetAuthError sets the "auth_error" field.
func (u *AccountUpsertOne) SetAuthError(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetAuthError(v)
	})
}

// UpdateAuthError sets the "auth_error" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateAuthError() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateAuthError()
	})
}

// ClearAuthError clears the value of the "auth_error" field.
func (u *AccountUpsertOne) ClearAuthError() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.ClearAuthError()
	})
}

// SetSyncNotice sets the "sync_notice" field.
func (u *AccountUpsertOne) SetSyncNotice(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetSyncNotice(v)
	})
}

// UpdateSyncNotice sets the "sync_notice" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateSyncNotice() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSyncNotice()
	})
}

// ClearSyncNotice clears the value of the "sync_notice" field.
func (u *AccountUpsertOne) ClearSyncNotice() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.ClearSyncNotice()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsertOne) SetUpdatedAt(v time.Time) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateUpdatedAt() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AccountUpsertOne.ID is not supported by MySQL driver. Use AccountUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
	conflict []sql.ConflictOption
}

// Save creates the Account entities in the database.
func (_c *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Account, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUpsertBulk {
	_c.conflict = opts
	return &AccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCreateBulk) OnConflictColumns(columns ...string) *AccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertBulk{
		create: _c,
	}
}

// AccountUpsertBulk is the builder for "upsert"-ing
// a bulk of Account nodes.
type AccountUpsertBulk struct {
	create *AccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(account.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountUpsertBulk) UpdateNewValues() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(account.FieldID)
			}
			if _, exists := b.mutation.Kind(); exists {
				s.SetIgnore(account.FieldKind)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(account.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUpsertBulk) Ignore() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertBulk) DoNothing() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUpsertBulk) Update(set func(*AccountUpsert)) *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *AccountUpsertBulk) SetDisplayName(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateDisplayName() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateDisplayName()
	})
}

// SetSettings sets the "settings" field.
func (u *AccountUpsertBulk) SetSettings(v map[string]interface{}) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateSettings() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSettings()
	})
}

// ClearSettings clears the value of the "settings" field.
func (u *AccountUpsertBulk) ClearSettings() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.ClearSettings()
	})
}

// SetNeedsReauth sets the "needs_reauth" field.
func (u *AccountUpsertBulk) SetNeedsReauth(v bool) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetNeedsReauth(v)
	})
}

// UpdateNeedsReauth sets the "needs_reauth" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateNeedsReauth() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateNeedsReauth()
	})
}

// SetAuthError sets the "auth_error" field.
func (u *AccountUpsertBulk) SetAuthError(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetAuthError(v)
	})
}

// UpdateAuthError sets the "auth_error" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateAuthError() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateAuthError()
	})
}

// ClearAuthError clears the value of the "auth_error" field.
func (u *AccountUpsertBulk) ClearAuthError() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.ClearAuthError()
	})
}

// SetSyncNotice sets the "sync_notice" field.
func (u *AccountUpsertBulk) SetSyncNotice(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetSyncNotice(v)
	})
}

// UpdateSyncNotice sets the "sync_notice" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateSyncNotice() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSyncNotice()
	})
}

// ClearSyncNotice clears the value of the "sync_notice" field.
func (u *AccountUpsertBulk) ClearSyncNotice() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.ClearSyncNotice()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsertBulk) SetUpdatedAt(v time.Time) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateUpdatedAt() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
