// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mecattaf/dcal/ent/invitationstate"
)

// InvitationState is the model entity for the InvitationState schema.
type InvitationState struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CalendarID holds the value of the "calendar_id" field.
	CalendarID string `json:"calendar_id,omitempty"`
	// UID holds the value of the "uid" field.
	UID string `json:"uid,omitempty"`
	// EventStart holds the value of the "event_start" field.
	EventStart time.Time `json:"event_start,omitempty"`
	// NotifiedAt holds the value of the "notified_at" field.
	NotifiedAt   time.Time `json:"notified_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvitationState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invitationstate.FieldID:
			values[i] = new(sql.NullInt64)
		case invitationstate.FieldCalendarID, invitationstate.FieldUID:
			values[i] = new(sql.NullString)
		case invitationstate.FieldEventStart, invitationstate.FieldNotifiedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvitationState fields.
func (_m *InvitationState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invitationstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case invitationstate.FieldCalendarID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field calendar_id", values[i])
			} else if value.Valid {
				_m.CalendarID = value.String
			}
		case invitationstate.FieldUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				_m.UID = value.String
			}
		case invitationstate.FieldEventStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field event_start", values[i])
			} else if value.Valid {
				_m.EventStart = value.Time
			}
		case invitationstate.FieldNotifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field notified_at", values[i])
			} else if value.Valid {
				_m.NotifiedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvitationState.
// This includes values selected through modifiers, order, etc.
func (_m *InvitationState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InvitationState.
// Note that you need to call InvitationState.Unwrap() before calling this method if this InvitationState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvitationState) Update() *InvitationStateUpdateOne {
	return NewInvitationStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvitationState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvitationState) Unwrap() *InvitationState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvitationState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvitationState) String() string {
	var builder strings.Builder
	builder.WriteString("InvitationState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("calendar_id=")
	builder.WriteString(_m.CalendarID)
	builder.WriteString(", ")
	builder.WriteString("uid=")
	builder.WriteString(_m.UID)
	builder.WriteString(", ")
	builder.WriteString("event_start=")
	builder.WriteString(_m.EventStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("notified_at=")
	builder.WriteString(_m.NotifiedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvitationStates is a parsable slice of InvitationState.
type InvitationStates []*InvitationState
