// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mecattaf/dcal/ent/invitationstate"
)

// InvitationStateCreate is the builder for creating a InvitationState entity.
type InvitationStateCreate struct {
	config
	mutation *InvitationStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCalendarID sets the "calendar_id" field.
func (_c *InvitationStateCreate) SetCalendarID(v string) *InvitationStateCreate {
	_c.mutation.SetCalendarID(v)
	return _c
}

// SetUID sets the "uid" field.
func (_c *InvitationStateCreate) SetUID(v string) *InvitationStateCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetEventStart sets the "event_start" field.
func (_c *InvitationStateCreate) SetEventStart(v time.Time) *InvitationStateCreate {
	_c.mutation.SetEventStart(v)
	return _c
}

// SetNotifiedAt sets the "notified_at" field.
func (_c *InvitationStateCreate) SetNotifiedAt(v time.Time) *InvitationStateCreate {
	_c.mutation.SetNotifiedAt(v)
	return _c
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_c *InvitationStateCreate) SetNillableNotifiedAt(v *time.Time) *InvitationStateCreate {
	if v != nil {
		_c.SetNotifiedAt(*v)
	}
	return _c
}

// Mutation returns the InvitationStateMutation object of the builder.
func (_c *InvitationStateCreate) Mutation() *InvitationStateMutation {
	return _c.mutation
}

// Save creates the InvitationState in the database.
func (_c *InvitationStateCreate) Save(ctx context.Context) (*InvitationState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvitationStateCreate) SaveX(ctx context.Context) *InvitationState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvitationStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvitationStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvitationStateCreate) defaults() {
	if _, ok := _c.mutation.NotifiedAt(); !ok {
		v := invitationstate.DefaultNotifiedAt()
		_c.mutation.SetNotifiedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvitationStateCreate) check() error {
	if _, ok := _c.mutation.CalendarID(); !ok {
		return &ValidationError{Name: "calendar_id", err: errors.New(`ent: missing required field "InvitationState.calendar_id"`)}
	}
	if v, ok := _c.mutation.CalendarID(); ok {
		if err := invitationstate.CalendarIDValidator(v); err != nil {
			return &ValidationError{Name: "calendar_id", err: fmt.Errorf(`ent: validator failed for field "InvitationState.calendar_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "InvitationState.uid"`)}
	}
	if v, ok := _c.mutation.UID(); ok {
		if err := invitationstate.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "InvitationState.uid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventStart(); !ok {
		return &ValidationError{Name: "event_start", err: errors.New(`ent: missing required field "InvitationState.event_start"`)}
	}
	if _, ok := _c.mutation.NotifiedAt(); !ok {
		return &ValidationError{Name: "notified_at", err: errors.New(`ent: missing required field "InvitationState.notified_at"`)}
	}
	return nil
}

func (_c *InvitationStateCreate) sqlSave(ctx context.Context) (*InvitationState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvitationStateCreate) createSpec() (*InvitationState, *sqlgraph.CreateSpec) {
	var (
		_node = &InvitationState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invitationstate.Table, sqlgraph.NewFieldSpec(invitationstate.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CalendarID(); ok {
		_spec.SetField(invitationstate.FieldCalendarID, field.TypeString, value)
		_node.CalendarID = value
	}
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(invitationstate.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.EventStart(); ok {
		_spec.SetField(invitationstate.FieldEventStart, field.TypeTime, value)
		_node.EventStart = value
	}
	if value, ok := _c.mutation.NotifiedAt(); ok {
		_spec.SetField(invitationstate.FieldNotifiedAt, field.TypeTime, value)
		_node.NotifiedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvitationState.Create().
//		SetCalendarID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvitationStateUpsert) {
//			SetCalendarID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvitationStateCreate) OnConflict(opts ...sql.ConflictOption) *InvitationStateUpsertOne {
	_c.conflict = opts
	return &InvitationStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvitationState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvitationStateCreate) OnConflictColumns(columns ...string) *InvitationStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvitationStateUpsertOne{
		create: _c,
	}
}

type (
	// InvitationStateUpsertOne is the builder for "upsert"-ing
	//  one InvitationState node.
	InvitationStateUpsertOne struct {
		create *InvitationStateCreate
	}

	// InvitationStateUpsert is the "OnConflict" setter.
	InvitationStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetCalendarID sets the "calendar_id" field.
func (u *InvitationStateUpsert) SetCalendarID(v string) *InvitationStateUpsert {
	u.Set(invitationstate.FieldCalendarID, v)
	return u
}

// UpdateCalendarID sets the "calendar_id" field to the value that was provided on create.
func (u *InvitationStateUpsert) UpdateCalendarID() *InvitationStateUpsert {
	u.SetExcluded(invitationstate.FieldCalendarID)
	return u
}

// SetUID sets the "uid" field.
func (u *InvitationStateUpsert) SetUID(v string) *InvitationStateUpsert {
	u.Set(invitationstate.FieldUID, v)
	return u
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *InvitationStateUpsert) UpdateUID() *InvitationStateUpsert {
	u.SetExcluded(invitationstate.FieldUID)
	return u
}

// SetEventStart sets the "event_start" field.
func (u *InvitationStateUpsert) SetEventStart(v time.Time) *InvitationStateUpsert {
	u.Set(invitationstate.FieldEventStart, v)
	return u
}

// UpdateEventStart sets the "event_start" field to the value that was provided on create.
func (u *InvitationStateUpsert) UpdateEventStart() *InvitationStateUpsert {
	u.SetExcluded(invitationstate.FieldEventStart)
	return u
}

// SetNotifiedAt sets the "notified_at" field.
func (u *InvitationStateUpsert) SetNotifiedAt(v time.Time) *InvitationStateUpsert {
	u.Set(invitationstate.FieldNotifiedAt, v)
	return u
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *InvitationStateUpsert) UpdateNotifiedAt() *InvitationStateUpsert {
	u.SetExcluded(invitationstate.FieldNotifiedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvitationState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvitationStateUpsertOne) UpdateNewValues() *InvitationStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvitationState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvitationStateUpsertOne) Ignore() *InvitationStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvitationStateUpsertOne) DoNothing() *InvitationStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvitationStateCreate.OnConflict
// documentation for more info.
func (u *InvitationStateUpsertOne) Update(set func(*InvitationStateUpsert)) *InvitationStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvitationStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCalendarID sets the "calendar_id" field.
func (u *InvitationStateUpsertOne) SetCalendarID(v string) *InvitationStateUpsertOne {
	return u.Update(func(s *InvitationStateUpsert) {
		s.SetCalendarID(v)
	})
}

// UpdateCalendarID sets the "calendar_id" field to the value that was provided on create.
func (u *InvitationStateUpsertOne) UpdateCalendarID() *InvitationStateUpsertOne {
	return u.Update(func(s *InvitationStateUpsert) {
		s.UpdateCalendarID()
	})
}

// SetUID sets the "uid" field.
func (u *InvitationStateUpsertOne) SetUID(v string) *InvitationStateUpsertOne {
	return u.Update(func(s *InvitationStateUpsert) {
		s.SetUID(v)
	})
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *InvitationStateUpsertOne) UpdateUID() *InvitationStateUpsertOne {
	return u.Update(func(s *InvitationStateUpsert) {
		s.UpdateUID()
	})
}

// SetEventStart sets the "event_start" field.
func (u *InvitationStateUpsertOne) SetEventStart(v time.Time) *InvitationStateUpsertOne {
	return u.Update(func(s *InvitationStateUpsert) {
		s.SetEventStart(v)
	})
}

// UpdateEventStart sets the "event_start" field to the value that was provided on create.
func (u *InvitationStateUpsertOne) UpdateEventStart() *InvitationStateUpsertOne {
	return u.Update(func(s *InvitationStateUpsert) {
		s.UpdateEventStart()
	})
}

// SetNotifiedAt sets the "notified_at" field.
func (u *InvitationStateUpsertOne) SetNotifiedAt(v time.Time) *InvitationStateUpsertOne {
	return u.Update(func(s *InvitationStateUpsert) {
		s.SetNotifiedAt(v)
	})
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *InvitationStateUpsertOne) UpdateNotifiedAt() *InvitationStateUpsertOne {
	return u.Update(func(s *InvitationStateUpsert) {
		s.UpdateNotifiedAt()
	})
}

// Exec executes the query.
func (u *InvitationStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvitationStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvitationStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvitationStateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvitationStateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvitationStateCreateBulk is the builder for creating many InvitationState entities in bulk.
type InvitationStateCreateBulk struct {
	config
	err      error
	builders []*InvitationStateCreate
	conflict []sql.ConflictOption
}

// Save creates the InvitationState entities in the database.
func (_c *InvitationStateCreateBulk) Save(ctx context.Context) ([]*InvitationState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvitationState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvitationStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvitationStateCreateBulk) SaveX(ctx context.Context) []*InvitationState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvitationStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvitationStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvitationState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvitationStateUpsert) {
//			SetCalendarID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvitationStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvitationStateUpsertBulk {
	_c.conflict = opts
	return &InvitationStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvitationState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvitationStateCreateBulk) OnConflictColumns(columns ...string) *InvitationStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvitationStateUpsertBulk{
		create: _c,
	}
}

// InvitationStateUpsertBulk is the builder for "upsert"-ing
// a bulk of InvitationState nodes.
type InvitationStateUpsertBulk struct {
	create *InvitationStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvitationState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvitationStateUpsertBulk) UpdateNewValues() *InvitationStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvitationState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvitationStateUpsertBulk) Ignore() *InvitationStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvitationStateUpsertBulk) DoNothing() *InvitationStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvitationStateCreateBulk.OnConflict
// documentation for more info.
func (u *InvitationStateUpsertBulk) Update(set func(*InvitationStateUpsert)) *InvitationStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvitationStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCalendarID sets the "calendar_id" field.
func (u *InvitationStateUpsertBulk) SetCalendarID(v string) *InvitationStateUpsertBulk {
	return u.Update(func(s *InvitationStateUpsert) {
		s.SetCalendarID(v)
	})
}

// UpdateCalendarID sets the "calendar_id" field to the value that was provided on create.
func (u *InvitationStateUpsertBulk) UpdateCalendarID() *InvitationStateUpsertBulk {
	return u.Update(func(s *InvitationStateUpsert) {
		s.UpdateCalendarID()
	})
}

// SetUID sets the "uid" field.
func (u *InvitationStateUpsertBulk) SetUID(v string) *InvitationStateUpsertBulk {
	return u.Update(func(s *InvitationStateUpsert) {
		s.SetUID(v)
	})
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *InvitationStateUpsertBulk) UpdateUID() *InvitationStateUpsertBulk {
	return u.Update(func(s *InvitationStateUpsert) {
		s.UpdateUID()
	})
}

// SetEventStart sets the "event_start" field.
func (u *InvitationStateUpsertBulk) SetEventStart(v time.Time) *InvitationStateUpsertBulk {
	return u.Update(func(s *InvitationStateUpsert) {
		s.SetEventStart(v)
	})
}

// UpdateEventStart sets the "event_start" field to the value that was provided on create.
func (u *InvitationStateUpsertBulk) UpdateEventStart() *InvitationStateUpsertBulk {
	return u.Update(func(s *InvitationStateUpsert) {
		s.UpdateEventStart()
	})
}

// SetNotifiedAt sets the "notified_at" field.
func (u *InvitationStateUpsertBulk) SetNotifiedAt(v time.Time) *InvitationStateUpsertBulk {
	return u.Update(func(s *InvitationStateUpsert) {
		s.SetNotifiedAt(v)
	})
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *InvitationStateUpsertBulk) UpdateNotifiedAt() *InvitationStateUpsertBulk {
	return u.Update(func(s *InvitationStateUpsert) {
		s.UpdateNotifiedAt()
	})
}

// Exec executes the query.
func (u *InvitationStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvitationStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvitationStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvitationStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
