repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.10.1
    hooks:
      - id: golangci-lint-fmt
        require_serial: true
        language_version: system
      - id: golangci-lint-full
        language_version: system
      - id: golangci-lint-config-verify
        language_version: system
  - repo: local
    hooks:
      - id: go-test
        name: go test
        entry: env CGO_ENABLED=0 go test ./...
        language: system
        pass_filenames: false
        types: [go]
