#!/usr/bin/env python3
"""render-tally-kit.py — render the box's tally KIT into home/dot_config/tally/kit.json.

RULING 4 (2026-09-16 evening). "Coordinator switching must NOT be required every
time a Tally flow is added. A new kit entry / flow must load without a
home-manager or NixOS switch. ... The kit path must become a runtime-read,
git-tracked location, not a store path baked at switch time."

So the kit stopped being `pkgs.writeText` in home/tally-uplink.nix and became
THIS file's committed output at home/dot_config/tally/kit.json, installed at
~/.config/tally/kit.json by an out-of-store symlink (the motion home/home.nix
already performs for the raw dotfiles). The uplink reads `--kit` fresh on every
timer wake (lake apps/uplink/src/kit.mjs `readKit` is a `readFileSync` per
pass), so an edit to the committed JSON is live at the next wake: a git commit,
never a switch.

WHY A RENDERER AND NOT A HAND-EDITED FILE. The CUBS campaign needs 3N entries
(one `build:CUBS-<n>` plus its `scope(...)` and `eval(...)` no-op cells, N=200),
which is 603 entries in total with the LOCAL-SMOKE trio. Hand-maintaining that
is how a table acquires a typo nobody reads. `lib.genList` used to do it inside
the module; this tool does it outside, deterministically, and `--check` is the
oracle that the committed bytes are the ones this tool renders. Editing a flow
by hand is still legal — that is the whole point of ruling 4 — but then either
this tool is edited to match or the entry moves out of the generated range.

EVERY argv[0] IS A STABLE PATH, NEVER A STORE PATH. A `/nix/store/<hash>-...`
argv inside a git-tracked file would re-introduce exactly what ruling 4
removed: the file would go stale the moment the package rebuilt, and refreshing
it would be a switch. So the two executables are named at their per-user
profile paths — `/etc/profiles/per-user/tom/bin/{tally-local-smoke,
cubs-iteration}` — which home.packages in home/tally-uplink.nix puts there and
which do not move when the derivation does. `tools/render-tally-kit.py --check`
plus `grep -c /nix/store home/dot_config/tally/kit.json` == 0 is the fence.

Usage:
  python3 tools/render-tally-kit.py           # write the JSON
  python3 tools/render-tally-kit.py --check   # rc 0 iff the committed bytes match
  python3 tools/render-tally-kit.py --stdout  # print, write nothing
"""

from __future__ import annotations

import argparse
import difflib
import json
import pathlib
import sys

# ------------------------------------------------------------------ CONSTANTS
#
# These are the literals home/tally-uplink.nix states on the nix side. They are
# repeated here rather than imported because this tool must run with python3 and
# nothing else — no nix, no network, no evaluation — which is what makes
# `--check` usable as a pre-commit fence and as a clause of the FT-3 probe. The
# flake's `tally-uplink-topology` check reads the RENDERED option and this file,
# so a drift between the two sides is red rather than silent.

HOME = "/home/tom"
REWRITE_STATE = f"{HOME}/.local/state/tally-rewrite"
USAGE_DIR = f"{REWRITE_STATE}/uplink/usage"
PROFILE_BIN = "/etc/profiles/per-user/tom/bin"

LOCAL_SMOKE_BIN = f"{PROFILE_BIN}/tally-local-smoke"
CUBS_BIN = f"{PROFILE_BIN}/cubs-iteration"

CUBS_CAMPAIGN_DIR = f"{HOME}/mecattaf/cubs-campaign"
CUBS_WORKLIST = f"{CUBS_CAMPAIGN_DIR}/worklists/current.jsonl"

# N is a ceiling on LABELS, not a promise of work (DECISIONS.md, 2026-09-16
# cubs-halogen-probe-1, line 2): a worklist line exists for an id or
# cubs-iteration exits 65 naming it, and an item the plan never mints has an
# entry nobody resolves.
CUBS_COUNT = 200

KIT_PATH = pathlib.Path("home/dot_config/tally/kit.json")

NOTE = [
    "The coordinator's KIT (U-D14, TL-18/D-B18, dotfiles#304). argv_ref -> the",
    "command, its cwd, the environment names it may see, where its usage record",
    "lands, and what it is handed on stdin.",
    "",
    "RUNTIME-READ AND GIT-TRACKED (ruling 4, 2026-09-16 evening). This file is",
    "home/dot_config/tally/kit.json in the dotfiles checkout, symlinked out of",
    "store to ~/.config/tally/kit.json, and the uplink reads it fresh on every",
    "timer wake. Adding a flow is an edit to this file and a commit — NEVER a",
    "home-manager or NixOS switch. Rule 9 (dotfiles#293, 'do not edit on the",
    "box') yields here to ruling 4: the reviewed artifact is the GIT OBJECT,",
    "not a store path, and review happens in the repository.",
    "",
    "Generated by tools/render-tally-kit.py; `--check` diffs the committed",
    "bytes against a fresh render. A hand edit is legal (that is ruling 4) but",
    "must be mirrored in the tool or made outside the generated ranges.",
    "",
    "EVERY argv[0] IS A STABLE PER-USER PROFILE PATH, never a hashed store",
    "path: a store path in a git-tracked file goes stale the moment the",
    "derivation rebuilds, and refreshing it would be the switch ruling 4",
    "removed. The fence is `grep -c` for the store prefix over this file == 0.",
    "",
    "ENABLED: build:LOCAL-SMOKE, a deterministic local job for the mechanical",
    "row. It writes one JSON line at $TALLY_USAGE_SOURCE_PATH carrying the",
    "$TALLY_EXECUTION_ID the kernel gave it, which is the usage_source join the",
    "witness_record points at.",
    "",
    "ENABLED: build:CUBS-1 .. build:CUBS-200 (+ scope/eval no-ops), the",
    "cubs-halogen-probe-1 campaign (FRONT-12 bootstrap): one executable,",
    "cubs-iteration, per item; stdin is a POINTER {worklist, id} into",
    "~/mecattaf/cubs-campaign/worklists/current.jsonl, resolved by the script.",
    "docs/local-ai/cubs-campaign.md.",
    "",
    "NOT ENABLED: claude:headless. The seat rows are feeder-owned (tally",
    "docs/rows.md:41-55, modules/tally-b.nix:57-63) and no kernel lease on a",
    "Claude seat is sanctioned; the ruling is asked in dotfiles#362. A proposal",
    "naming it is refused by name against this file, which is the intended",
    "outcome and not a gap.",
    "",
    "usage_source.kind is an OPAQUE label the kernel carries and never reads",
    "(tally docs/transport.md section 2). It names no harness and nothing",
    "branches on it.",
]


def noop_entry(kind: str, glob: str) -> dict:
    """The declared no-op cell beside a job.

    `/bin/sh -c true`, NOT `/bin/true`: MEASURED on this box, /bin holds exactly
    one entry, `sh`, a symlink into the store; an argv naming /bin/true would
    attest a spawn failure rather than the pass the cell is about. The lake's
    own fixture (fixtures/uplink/kit.json) says the same thing.
    """
    return {
        "argv": ["/bin/sh", "-c", "true"],
        "cwd": "/",
        "env_allowlist": [],
        "usage_source": {"kind": kind, "path_glob": f"{USAGE_DIR}/{glob}-*.jsonl"},
        "stdin": "",
    }


def local_smoke_entry() -> dict:
    return {
        "argv": [LOCAL_SMOKE_BIN],
        "cwd": f"{REWRITE_STATE}/uplink",
        "env_allowlist": [],
        "usage_source": {
            "kind": "tally-usage/1",
            "path_glob": f"{USAGE_DIR}/local-smoke-*.jsonl",
        },
        "stdin": "",
    }


def cubs_entry(item_id: str) -> dict:
    """One CUBS iteration.

    `stdin` is a POINTER and not the task (DECISIONS.md 2026-09-16, line 1):
    the entry hands over {worklist, id} and cubs-iteration resolves the task
    line from the worklist the morning review re-points, so a day's worklist
    never touches this file.
    """
    return {
        "argv": [CUBS_BIN],
        "cwd": CUBS_CAMPAIGN_DIR,
        "env_allowlist": [],
        "usage_source": {
            "kind": "halogen-usage/1",
            "path_glob": f"{USAGE_DIR}/cubs-*.jsonl",
        },
        "stdin": json.dumps({"worklist": CUBS_WORKLIST, "id": item_id}, separators=(",", ":"))
        + "\n",
    }


def render() -> str:
    entries: dict[str, dict] = {
        "build:LOCAL-SMOKE": local_smoke_entry(),
        "scope(build:LOCAL-SMOKE)": noop_entry("opaque-noop/1", "scope-noop"),
        "eval(build:LOCAL-SMOKE)": noop_entry("opaque-noop/1", "eval-noop"),
    }
    for n in range(1, CUBS_COUNT + 1):
        item_id = f"CUBS-{n}"
        entries[f"build:{item_id}"] = cubs_entry(item_id)
        entries[f"scope(build:{item_id})"] = noop_entry("opaque-noop/1", "scope-noop")
        entries[f"eval(build:{item_id})"] = noop_entry("opaque-noop/1", "eval-noop")
    return json.dumps({"_note": NOTE, "entries": entries}, indent=2) + "\n"


def repo_root() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parent.parent


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="rc 0 iff the committed bytes match")
    ap.add_argument("--stdout", action="store_true", help="print the render, write nothing")
    args = ap.parse_args()

    target = repo_root() / KIT_PATH
    text = render()

    if args.stdout:
        sys.stdout.write(text)
        return 0

    if args.check:
        if not target.exists():
            print(f"render-tally-kit: {KIT_PATH} does not exist", file=sys.stderr)
            return 1
        have = target.read_text()
        if have == text:
            entries = json.loads(text)["entries"]
            print(f"render-tally-kit --check: {KIT_PATH} matches ({len(entries)} entries)")
            return 0
        diff = difflib.unified_diff(
            have.splitlines(keepends=True),
            text.splitlines(keepends=True),
            fromfile=f"a/{KIT_PATH}",
            tofile="b/render-tally-kit.py",
        )
        sys.stderr.writelines(diff)
        print(f"render-tally-kit --check: {KIT_PATH} is NOT the rendered bytes", file=sys.stderr)
        return 1

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)
    entries = json.loads(text)["entries"]
    print(f"render-tally-kit: wrote {KIT_PATH} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
